### ISSUE TITLE
Weird build errors

### ISSUE THREAD

**Issue by v1993** [visualboyadvance-m/visualboyadvance-m#392] opened 2019-03-19 11:33 UTC
### Expected behavior
VBA-M builds normally using CMake and clang.

### Actual behavior
```
v@v-xubuntu:~/compile/visualboyadvance-m/build$ cmake .. -GNinja -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_C_COMPILER=clang -DCMAKE_INSTALL_PREFIX=/home/v/.local
… (Runs fine)
v@v-xubuntu:~/compile/visualboyadvance-m/build$ ninja -j8
… (Compilation with a lot of warnings about register spec deprecation)
[185/185] Linking CXX executable visualboyadvance-m
FAILED: visualboyadvance-m
: && ccache /usr/bin/clang++  -pthread -O3 -DNDEBUG  -rdynamic src/wx/CMakeFiles/visualboyadvance-m.dir/wxvbam.cpp.o src/wx/CMakeFiles/visualboyadvance-m.dir/guiinit.cpp.o src/wx/CMakeFiles/visualboyadvance-m.dir/viewers.cpp.o src/wx/CMakeFiles/visualboyadvance-m.dir/gfxviewers.cpp.o src/wx/CMakeFiles/visualboyadvance-m.dir/cmdevents.cpp.o src/wx/CMakeFiles/visualboyadvance-m.dir/opts.cpp.o src/wx/CMakeFiles/visualboyadvance-m.dir/sys.cpp.o src/wx/CMakeFiles/visualboyadvance-m.dir/panel.cpp.o src/wx/CMakeFiles/visualboyadvance-m.dir/viewsupt.cpp.o src/wx/CMakeFiles/visualboyadvance-m.dir/wayland.cpp.o src/wx/CMakeFiles/visualboyadvance-m.dir/strutils.cpp.o src/wx/CMakeFiles/visualboyadvance-m.dir/widgets/keyedit.cpp.o src/wx/CMakeFiles/visualboyadvance-m.dir/widgets/joyedit.cpp.o src/wx/CMakeFiles/visualboyadvance-m.dir/widgets/sdljoy.cpp.o src/wx/CMakeFiles/visualboyadvance-m.dir/widgets/wxmisc.cpp.o src/wx/CMakeFiles/visualboyadvance-m.dir/__/sdl/text.cpp.o src/wx/CMakeFiles/visualboyadvance-m.dir/widgets/checkedlistctrl.cpp.o src/wx/CMakeFiles/visualboyadvance-m.dir/cmdtab.cpp.o  -o visualboyadvance-m -L/home/v/compile/visualboyadvance-m/build -Wl,-rpath,/home/v/compile/visualboyadvance-m/build libvbamcore.a fex/libfex.a -Wl,-Bstatic -lSDL2main -Wl,-Bdynamic -lSDL2 -lpthread -lsfml-network -lsfml-system -lGL -lGLU -lz -lpng -lrt -lpthread -L/usr/lib/x86_64-linux-gnu -pthread -lwx_gtk2u_xrc-3.0 -lwx_baseu_xml-3.0 -lwx_gtk2u_html-3.0 -lwx_gtk2u_adv-3.0 -lwx_baseu_net-3.0 -lwx_gtk2u_core-3.0 -lwx_baseu-3.0 -lwx_gtk2u_gl-3.0 -lgtk-x11-2.0 -lgdk-x11-2.0 -lpangocairo-1.0 -latk-1.0 -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lpangoft2-1.0 -lpango-1.0 -lgobject-2.0 -lglib-2.0 -lfontconfig -lfreetype  -pipe -Wformat -Wformat-security -D_FORTIFY_SOURCE=2 -feliminate-unused-debug-types -fPIC -mfpmath=sse -msse2 -O2 -fomit-frame-pointer -flto -mtune=generic -Wno-error  && :
/usr/bin/ld: libvbamcore.a: error adding symbols: archive has no index; run ranlib to add one
clang: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.
(Normal build failed, below is how I fix it manually)
v@v-xubuntu:~/compile/visualboyadvance-m/build$ llvm-ranlib libvbamcore.a
v@v-xubuntu:~/compile/visualboyadvance-m/build$ ninja -j8
[1/1] Linking CXX executable visualboyadvance-m
FAILED: visualboyadvance-m
: && ccache /usr/bin/clang++  -pthread -O3 -DNDEBUG  -rdynamic src/wx/CMakeFiles/visualboyadvance-m.dir/wxvbam.cpp.o src/wx/CMakeFiles/visualboyadvance-m.dir/guiinit.cpp.o src/wx/CMakeFiles/visualboyadvance-m.dir/viewers.cpp.o src/wx/CMakeFiles/visualboyadvance-m.dir/gfxviewers.cpp.o src/wx/CMakeFiles/visualboyadvance-m.dir/cmdevents.cpp.o src/wx/CMakeFiles/visualboyadvance-m.dir/opts.cpp.o src/wx/CMakeFiles/visualboyadvance-m.dir/sys.cpp.o src/wx/CMakeFiles/visualboyadvance-m.dir/panel.cpp.o src/wx/CMakeFiles/visualboyadvance-m.dir/viewsupt.cpp.o src/wx/CMakeFiles/visualboyadvance-m.dir/wayland.cpp.o src/wx/CMakeFiles/visualboyadvance-m.dir/strutils.cpp.o src/wx/CMakeFiles/visualboyadvance-m.dir/widgets/keyedit.cpp.o src/wx/CMakeFiles/visualboyadvance-m.dir/widgets/joyedit.cpp.o src/wx/CMakeFiles/visualboyadvance-m.dir/widgets/sdljoy.cpp.o src/wx/CMakeFiles/visualboyadvance-m.dir/widgets/wxmisc.cpp.o src/wx/CMakeFiles/visualboyadvance-m.dir/__/sdl/text.cpp.o src/wx/CMakeFiles/visualboyadvance-m.dir/widgets/checkedlistctrl.cpp.o src/wx/CMakeFiles/visualboyadvance-m.dir/cmdtab.cpp.o  -o visualboyadvance-m -L/home/v/compile/visualboyadvance-m/build -Wl,-rpath,/home/v/compile/visualboyadvance-m/build libvbamcore.a fex/libfex.a -Wl,-Bstatic -lSDL2main -Wl,-Bdynamic -lSDL2 -lpthread -lsfml-network -lsfml-system -lGL -lGLU -lz -lpng -lrt -lpthread -L/usr/lib/x86_64-linux-gnu -pthread -lwx_gtk2u_xrc-3.0 -lwx_baseu_xml-3.0 -lwx_gtk2u_html-3.0 -lwx_gtk2u_adv-3.0 -lwx_baseu_net-3.0 -lwx_gtk2u_core-3.0 -lwx_baseu-3.0 -lwx_gtk2u_gl-3.0 -lgtk-x11-2.0 -lgdk-x11-2.0 -lpangocairo-1.0 -latk-1.0 -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lpangoft2-1.0 -lpango-1.0 -lgobject-2.0 -lglib-2.0 -lfontconfig -lfreetype  -pipe -Wformat -Wformat-security -D_FORTIFY_SOURCE=2 -feliminate-unused-debug-types -fPIC -mfpmath=sse -msse2 -O2 -fomit-frame-pointer -flto -mtune=generic -Wno-error  && :
/usr/bin/ld: fex/libfex.a: error adding symbols: archive has no index; run ranlib to add one
clang: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.
(Great, another lib to fix)
v@v-xubuntu:~/compile/visualboyadvance-m/build$ llvm-ranlib fex/libfex.a
v@v-xubuntu:~/compile/visualboyadvance-m/build$ ninja -j8
[1/1] Linking CXX executable visualboyadvance-m
(And now we're fine)
```

### Steps to reproduce the behavior
I guess that this can be reproduced using commands from previous section. You'll need ninja build tool and clang/llvm. All the stuff is done on Ubuntu 18.10.

### Crash bugs

_If this is a crash bug_, and it is not one.

### ROM details

Which games are affected by the issue (please state if GBA or GB game): pretty much all of them because it prevents emulator from building and running.

Which games, if any, are NOT affected by the issue (please state if GBA or GB game):

Include screenshots of ROM Information (File > ROM Information):

### Build details

Operating System (Windows, Mac, Linux (state distribution), etc.): Ubuntu 18.10

If using Linux, specify if using xorg or Wayland: XOrg, but who cares at this step.

Version of code (pre-built binary version, or commit ref, or just "master"): git master (commit c714ff825a93cc1e5e76c6aaee76d0cb4f427601)

### Hardware details:

Nothing related to problem.

**Comment by rkitover** [comment] 2019-03-19 15:13
So if the issue is that cmake is supposed to use `llvm-ranlib` and not regular `ranlib`, how is it supposed to know this? Is there perhaps a toolchain file for clang you are supposed to use?

**Comment by rkitover** [comment] 2019-03-19 15:15
Another option is to use a `bin/` directory in your path, with symlinks to all the tools you want, e.g. `ranlib -> llvm-ranlib`, `cc -> clang`, `c++ -> clang++`.

**Comment by rkitover** [comment] 2019-03-20 01:43
Fixed in master btw, at least for this project, you will have this problem with other projects.

**Closed** 2019-03-20 01:44 UTC
Labels: bug, build, fixed

**Comment by v1993** [comment] 2019-03-21 08:57
I've used clang for a lot of other projects (including ones where static libs are built first and then linked together), never met any errors. That's weird part for me.

I'll try git master, thanks.

**Comment by v1993** [comment] 2019-03-21 09:00
As a sidenote, is VBA-M using SDL (not SDL2) for joysticks? Because it's probably only one place where they act like uncalibrated ones.

**Comment by rkitover** [comment] 2019-03-21 10:59
Yes SDL2 is used for joystick, if there is a better thing we can use I could switch.
