### ISSUE TITLE
Emulator freezes without access to Internet.

### ISSUE THREAD

**Issue by edorax** [visualboyadvance-m/visualboyadvance-m#71] opened 2017-02-11 03:28 UTC
### Expected behavior
It doesn't freeze.

### Actual behavior
If there's no access to the Internet, the emulator freezes after the main window appears at startup.

### Steps to reproduce the behavior
On Windows:
Disable the NIC or simple unplug the wire, then run the emulator. 

  void GameArea::OnIdle(wxIdleEvent& event)
  {
    ...
    // Check for online updates
    if (gopts.onlineupdates > 0 && !emusys) {
 // stuck here
 ->      wxGetApp().frame->CheckForUpdates();
    }
    ...
  }

### Build details
1. Setup the build system of MXE with:
     https://github.com/visualboyadvance-m/mxe
   Installed package needed by vba-m in MXE: wxwidgets, sdl2 he sfml, etc.
   Preppend the directory of usr/bin of MXE to the PATH env var.   
2. Pull the vba-m source from this Git repo:
      git clone https://github.com/visualboyadvance-m/visualboyadvance-m.git
3. Create makefile:
  unset `env | grep -vP '^\t' | grep -vi '^EDITOR=\|^HOME=\|^LANG=\|MXE\|^PATH=' | grep -vi 'PKG_CONFIG\|PROXY\|^PS1=\|^TERM=' | cut -d '=' -f1 | tr '\n' ' '`
  BUILD_DIR=build-vbam-mxe
  rm -rf ${BUILD_DIR} \
      && mkdir ${BUILD_DIR} \
      && cd ${BUILD_DIR} \
      && i686-w64-mingw32.static-cmake \
          ../vba-m/visualboyadvance-m
4. Make it: 
  make -C ${BUILD_DIR}

Operating System (Windows, Mac, Linux, etc.):
   Host OS: Ubuntu 16.04 LTS (64bit)
   Target OS: Windows 7 (64bit)

Interface (wx, SDL, default is wx):
Is wx. 

Version of code (pre-built binary version, or commit ref, or just "master"):
master

Any other relevant build information:

If this is e.g. a joystick or video issue, then the relevant hardware information:

**Comment by DoctorWho11** [comment] 2017-02-11 03:32
The issue is known and will be changed eventually. Will keep this up anyways.

**Comment by rkitover** [comment] 2017-02-12 11:56
Fixed in a493e0f8.

We need to reimplement the executable updating and ROM database updating using something like Sparkle at some point.

**Comment by rkitover** [comment] 2017-02-12 11:58
@edorax btw, on Ubuntu you can use:

```bash
./installdeps win32
```

to install all MXE deps automatically.

**Closed** 2017-02-13 09:21 UTC
Labels: bug, fixed
