### ISSUE TITLE
[Bug]: Default turbo speed when loading ROM and sound driver failure

### ISSUE THREAD

**Issue by Denzeduous** [visualboyadvance-m/visualboyadvance-m#946] opened 2022-04-21 19:57 UTC
### Expected behavior?

Game should load up the ROM and play

### Actual behavior?

I have tried the nightly and factory resetting it, but on Windows 10, when I load a ROM, it goes at an incredibly fast speed and also can't initialize the sound driver.

### Steps to reproduce the problem

1. Download nightly
2. Factory reset
3. Open a GBA rom
4. Can't initialize the sound driver error pops up
5. Game plays at way too fast of a speed

### What game were you playing

<Some of this information can be provided with a screenshot of Rom Information, SAVE TYPE for GBA titles can be obtained from Options > Game Boy Advance > Config>
Title: Pokemon Sapphire
GB, GBC or GBA: GBA
Don't know the rest

### What settings are you using?

Video driver (simple, opengl): Tried both
Sound driver (directsound, xaudio, openal, SDL): Tried SDL, DirectSound, and OpenAl
Scale Filter Used?: None

### Specifications and Build details

VBA-M: nightly 64bit
OS: (include version and OS build number using WinVer if on Windows): Windows 10
CPU: Ryzen 5 3950X 
GPU: Radeon RX 5700 XT
RAM: 64GB

### Copyright Compliance

- [X] There are no infringing files attached to this bug report.

**Comment by Squall-Leonhart** [comment] 2022-04-21 20:20
Duplicate of #851

**Closed by Squall-Leonhart** 2022-04-21 20:20 UTC
Labels: bug
