### ISSUE TITLE
2.0.1: Many settings are not saved between sessions

### ISSUE THREAD

**Issue by wfowler1** [visualboyadvance-m/visualboyadvance-m#196] opened 2018-02-12 05:50 UTC
### Expected behavior
Settings should be saved between sessions.

### Actual behavior
The following settings aren't being saved and/or loaded between sessions:
Video > Multithread Filter
Audio Device in Sound Settings dialog, Advanced tab (backend selection saves just fine)
Everything under Input > Autofire (I'm not sure these were ever meant to be saved though)
In Game Boy Advance Settings dialog, Flash size and Boot ROM path
In GameBoy settings dialog, both boot ROM paths
Everything in Directories (GBA ROMs, GB ROMs, Native saves, etc.)

### Steps to reproduce the behavior
1. Open the emulator
2. Change any of the above settings, I tend to set up GBA BIOS path and native battery save paths.
3. Close the emulator completely
4. Open the emulator again
5. Notice any of the settings listed above you changed have reverted to default/blank values.

Looking in my user folder under "AppData\Local\visualboyadvance-m\vbam.ini" it looks like the settings are saving properly, changes are being made and saved into that file. The emulator seems to simply ignore them when opening.

### Crash bugs
Probably not related, but I noticed that changing the "Check for updates" frequency setting causes the emulator to close completely when changed after you click the "OK" button. I'd love to provide a backtrace but that involves making a new build on a Linux machine for some reason.

### Build details

Operating System (Windows, Mac, Linux (state distribution), etc.):
Windows 10. I noticed this on three different machines so far. Doesn't matter whether you run the program as administrator or not.

Version of code (pre-built binary version, or commit ref, or just "master"):
Version 2.0.1 downloaded from GitHub. Haven't been able to try the latest revisions from the source code since I can't find any place to download more recent builds, and the build instructions are not Windows/MSVC friendly.

**Comment by wfowler1** [comment] 2018-02-12 05:55
Looks like issue #194 is referring at least partially to the same issue, though the creator goes into detail about many other things as well...

**Comment by twinters007** [comment] 2018-02-28 15:32
Keyboard bindings aren't saved as well. Very irritating to accidentally press escape and have the entire program quit

**Comment by ZachBacon** [comment] 2018-02-28 15:49
I just recently threw up a 64bit binary for Windows in the release tab that /should/ fix the issue, please test, I'll throw up a win32 binary shortly as well as a MacOS binary.

**Comment by Vyvyn-Crux** [comment] 2018-03-06 02:42
I can confirm it's not saving directories, File settings and changes to input still doesn't seem to work right. (IE: Loading ALLEYWAY for classic GB, The start button seems to have become assosiated with R Button, And the paddle is automatically moved into the left side of the screen. This same rom works flawlessly in earlier versions of the older VGBA)

**Comment by ZachBacon** [comment] 2018-03-06 02:43
@Vyvyn-Crux Did you test the latest development test build?

**Comment by Vyvyn-Crux** [comment] 2018-03-06 02:58
@ZachBacon tried vbam-2.0.1.7z on the releases page. I'm still new to how github is set up.

**Comment by ZachBacon** [comment] 2018-03-06 02:59
https://github.com/visualboyadvance-m/visualboyadvance-m/releases/tag/c7c6ad6

**Comment by Vyvyn-Crux** [comment] 2018-03-06 03:00
@ZachBacon: Thanks. I avoided that one because it said it wasn't a release release. I'll give it a shot and let you know how it works out.

**Comment by ZachBacon** [comment] 2018-03-06 03:00
It's a test build that has a fix for the settings issue

**Comment by wfowler1** [comment] 2018-03-06 03:18
I tested the build linked in the issue thread for #153 and it seems to work. I didn't test every single setting I listed above but I can confirm that at least Directory and BIOS settings are being saved and loaded properly now. I haven't noticed any other bugs introduced in this version either.

**Comment by Vyvyn-Crux** [comment] 2018-03-06 05:01
Seems to work here too. Won't know if it's the same case on the tablet though till the 32bit version is pushed.

**Comment by aloffensand** [comment] 2018-03-06 11:16
I just compiled the latest version, the paths set in Options/Directories now work, but the other settings mentioned above still don't work for me (the bios files for GBA and GB, Video/Multithread Filter, Audio Device and Autofire). Tested under Arch Linux.

**Comment by denisfa** [comment] 2019-07-18 16:24
@rkitover From everything here, only the `autofire` is not being remembered... Are these intended to persist too?

**Comment by rkitover** [comment] 2019-07-18 19:46
No we probably don't want to persist autofire.

**Comment by rkitover** [comment] 2019-08-15 15:26
@denisfa can we close this now?

**Comment by denisfa** [comment] 2019-08-19 16:25
@rkitover Yes, everything here is ok now.

This was fixed in several commits and will be available next release. The only notice is that we don't want autofire to persist, at least for now.

**Closed by denisfa** 2019-08-19 16:25 UTC
Labels: bug, config, partially fixed
