### ISSUE TITLE
Link not working with 2 emulators of pokemon fire red, same computer - Communication Error

### ISSUE THREAD

**Issue by matanshukry** [visualboyadvance-m/visualboyadvance-m#769] opened 2020-10-27 10:46 UTC
### Expected behavior
Link work and trading enabled

### Actual behavior
Getting an error:;
```
Communication Error...
Please check all connections,
then turn the power OFF and ON
```

![image](https://user-images.githubusercontent.com/5613042/97290872-d337d000-1851-11eb-87eb-17be8dd30491.png)

### Steps to reproduce the behavior

1. Open vba-m and load the separate save files
2. In each of them, set the various modes:
`Options -> Link -> Speed Hack`
`Options -> Link -> Type -> Cable`
`Options -> GameBoyAdvanccd -> Configure -> Game Overrides -> Real Time Clock: Enabled`
`Options -> GameBoyAdvanccd -> Configure -> Save Type -> 128k`
`Emulation -> Pause when inactive (verify NOT checked)`

3. Go to Options -> Link -> Start network link
3.1 In the first use server and listen
3.2 In the second use client and connect

4. In each of them, inside the game go to the room and try to connect.
5. Once connected, they will try to go into the room.
Once in the room - you will see the error

### ROM details

Which games are affected by the issue (please state if GBA or GB game):
`GBA - Pokemon Fire Red U v1.1`

Include screenshots of ROM Information (File > ROM Information):
![image](https://user-images.githubusercontent.com/5613042/97291183-3b86b180-1852-11eb-8e7c-81e6a8db7f09.png)

### Option details

Video driver (simple, opengl): `opengl`

Sound driver (directsound, xaudio, openal, SDL): `SDL`

### Build details

Operating System (Windows, Mac, Linux (state distribution), etc.):
Windows

Version of code (pre-built binary version, or commit ref, or just "master"):
2.14

**Comment by JackoboLeChocobo** [comment] 2020-11-23 21:21
Question : I don't have the issue with old link cable code on my project but I want to test it on visualboyadvance-m. Have you tried to test the game on 2 computers ( PC1 = SERVER (Player 1) and PC2 = CLIENT (Player 2) ) if you can of course ?

**Comment by JackoboLeChocobo** [comment] 2020-11-23 22:48
Tested with Type "Cable" with the option "Start Network Link" on the same computer. Trading worked and leaves the room worked too. I met fps down after the connexion to the server (before entering the room).

**Comment by matanshukry** [comment] 2020-11-24 08:20
@JackoboLeChocobo 

> Question : I don't have the issue with old link cable code on my project but I want to test it on visualboyadvance-m. Have you tried to test the game on 2 computers ( PC1 = SERVER (Player 1) and PC2 = CLIENT (Player 2) ) if you can of course ?

I don't have 2 PCs to test it, no.



> Tested with Type "Cable" with the option "Start Network Link" on the same computer (timeout = 500ms). Trading worked and leaves the room worked too. I met fps down after the connexion to the server (before entering the room). FPS back to normal after exiting the room.

It doesn't work to me. I don't always get the same black screen error though, sometimes I just get a message box (like when characters talk in the game) that says
```Sorry, we have a link error...
Please reset and try again.```

If there are logs to find out more info, I can't find them.


p.s.
My timeout is set to 10s (10000 ms)

**Comment by JackoboLeChocobo** [comment] 2020-11-24 09:24
Yeah I see what message box you had ( I test some modifications and I had this message box).

Question N°1 : Why do you use a high timeout value ?
Question N°2 : Do you have this message on the terminal ( like on xterm in linux for instance )? ( Warning: Partial sends might not be handled properly )

**Comment by matanshukry** [comment] 2020-11-24 14:32
> Question N°1 : Why do you use a high timeout value ?
I remember reading I should use 500ms. I tried that and it didn't work, so I tried higher value.
Generally speaking higher values shoulnd't introduce new issues, but I tried lower values as well anyway.

> Question N°2 : Do you have this message on the terminal ( like on xterm in linux for instance )?
I'm using Windows, so I don't have any of those terminals.

**Comment by JackoboLeChocobo** [comment] 2020-11-25 06:21
After losing hairs because of SFML code (i tried so much to keep it seriously...), I tested the latest git code of visualboyadvance-m but with my GBA Link code. After some modifications ( many months since the last version of WVBAL ), I tested the GBA Link code on RetroArch with this game and... it works without issue. Native code of network is in my opinion a best solution than using a framework (like in Javascript on Web Dev, it is better to use native code than JQUERY). My code for Linux and denopqrihg's code for Windows (original author of VBALink, thanks to his works that I have created the Linux version) may have 8-9 years : it still works. I tried the Coliseum and the exchange of Pokemon for information on the same computer. Timeout used : 500ms.

**Comment by matanshukry** [comment] 2020-11-25 10:05
@JackoboLeChocobo .. not sure how what you're wrote is relevant to this issue.

I understand it works for you on Linux.
It doesn't work for me on Windows, and there doesn't seem to be any way to find relevant logs.

**Comment by JackoboLeChocobo** [comment] 2020-11-25 10:59
Code that I use works on Windows too and are based totally on denopqrihg's code.
I don't see an option to activate logs about that. I know it is an old gba version but to verify that, test your game with the original VBALink project here : "http://www.vbalink.info/" -> Downloads here : http://www.vbalink.info/download-gba-emulator.htm

Try to begin with that to see if you have still the issue

**Comment by matanshukry** [comment] 2020-11-25 11:13
Vba link emulators are unable to open the game at all; it just shows a completely white screen forever.
I tried both 1.72 and 1.8

**Comment by JackoboLeChocobo** [comment] 2020-11-27 13:01
Very strange... If someone can test visualboyadvance-m in their computers with this game to see if the same issue is present, we can move all together to find solutions... I will recheck the sfml side ( native socket code works so link code has a bug here ) : Time to take cookies and coffee :3

**Comment by JackoboLeChocobo** [comment] 2020-11-28 17:21
I will create a new issue about Link in general and do some explanations here. I do one test about modifications on GBA.cpp and GBALink,cpp that uses always SFML but Pokemon Fire Red here has now the issue that you have and before thanks to slow FPS the game connected without issue.

**Comment by rkitover** [comment] 2020-11-29 01:24
@JackoboLeChocobo Please give me a name and email address so I can attribute git commits to you, it can be any name and email address you like.

**Comment by JackoboLeChocobo** [comment] 2020-11-29 22:29
Before that, because I don't want to do mistakes on the project, I found the problem about pokemon here and that affects others games too. I will explain in an general issue. After we found how to resolv that, only with this condition I will communicate to you a name and an email address for the commits ^^ The issue will have the tag [LINK] on the title . Sorry for the late answers : i do test from 9am to now today.

**Comment by JackoboLeChocobo** [comment] 2020-11-29 22:56
https://github.com/visualboyadvance-m/visualboyadvance-m/issues/786

**Comment by WinterAlexander** [comment] 2021-04-07 00:42
I'm also unable to connect. I have tried many configurations between several games (Leaf Green, Ruby and Emerald). I tried both on the same computer and also with 2 computers. Both computers are arch linux with latest version 2.1.4. There was a single attempt where I could enter the trading room (otherwise I had the message "Link/Transmission error" before entering the room. The single attempt ended when I unfocused one of the window to move the other player. At that time pause when inactive was unchecked. Could not get a second successfuly attempt after that.

Pause when inactive is unchecked
Timeout is 500ms
Link type: Cable
Local mode unchecked
Speed hack unchecked and no speedhack being used during the trade
Tried both with and without real time clock

Is there a version that works with trades on linux? I think I'll try https://www.vbalink.info/download-gba-emulator.htm but this is windows only unfortunately

**Comment by WinterAlexander** [comment] 2021-04-07 14:07
Update: VBA link on windows works great but only with "One computer" checked. Meanwhile the latest version of visualboyadvance-m works great for gamecube.

**Comment by killerwife** [comment] 2022-08-14 08:51
I can confirm this bug for Pokemon Emerald. It works when we link, we select pokemon to trade and the trade commences and then it throws: Communication Error.

**Comment by Squall-Leonhart** [comment] 2022-08-14 08:52
we don't need confirmations of bugs in the linking capability, issues are long known.

**Comment by SickProdigy** [comment] 2023-03-05 19:12
Having an issue currently with this out of box. Also on windows currently. Acts like it is about to connect and doesn't.

**Comment by Squall-Leonhart** [comment] 2023-04-11 03:14
This is more or less resolved by fine tuning the link timeouts. 500ms seems to be fine for the pokemon games, while 4 swords needs under 50.

**Closed by Squall-Leonhart** 2023-04-11 03:14 UTC
Labels: bug, link
