### ISSUE TITLE
[LINK] Controller only works on one screen at a time

### ISSUE THREAD

**Issue by SoulStriker27** [visualboyadvance-m/visualboyadvance-m#702] opened 2020-07-16 01:12 UTC
# Expected behavior
Open 2 windows of visual boy and play with different controllers.

### Actual behavior

I have to click on each window to play on that window. (Pause when inactive is disabled)

### Steps to reproduce the behavior

Just open up 2 windows, load Link to the Past/Four Swords, watch as the same controller works on one screen at a time

### ROM details

Which games are affected by the issue (please state if GBA or GB game): 
Link to the Past/Four Swords - GBA

Include screenshots of ROM Information (File > ROM Information):
![Capture](https://user-images.githubusercontent.com/46726808/87614059-ab729100-c6d4-11ea-8dba-2b37bb8b056d.PNG)

If you are using a BIOS file, please say which one: 
GBA Bios

### Option details

Video driver (simple, opengl): 
opengl

Sound driver (directsound, xaudio, openal, SDL):
SDL

### Build details

Operating System (Windows, Mac, Linux (state distribution), etc.): 
Windows 10 

Version of code (pre-built binary version, or commit ref, or just "master"): 
Nightly

1060 GeForce3gb, i5 3300k

**Comment by SoulStriker27** [comment] 2020-07-16 01:24
I apparently made it work at 2 screens at a time if you don't click any screen at all. Yet clicking 1 will force you to only play on that one.

**Comment by v1993** [comment] 2020-07-25 17:24
I think this is a duplicate of #207. This issue is also not related to link issues being mainly about input handling (it's problem in input system that begins to play a role once link feature is used).

Also, deselecting all windows won't do the trick on Linux.

**Comment by v1993** [comment] 2020-07-25 20:44
Check #705, that should fix this issue.

**Comment by SoulStriker27** [comment] 2020-07-26 02:36
How long before it is a part of the nightly build?

**Comment by rkitover** [comment] 2020-07-26 10:36
Once it is reviewed and any issues are resolved and it's merged to master.

It needs some more polishing at first glance.

**Closed** 2022-11-29 01:04 UTC
Labels: bug, link, input
