### ISSUE TITLE
Golden Sun games are unplayable due to several glitches

### ISSUE THREAD

**Issue by ShadowStkr** [visualboyadvance-m/visualboyadvance-m#144] opened 2017-08-25 07:54 UTC
### Expected behavior

The game should render the graphics and move sprites like the GBA does.

### Actual behavior

As soon as you pass through the naming screen and the main character (Isaac) goes out of bed, everything in the game gets glitchy. Isaac's sprite, which should just jump out of the bed, goes right until it's off-screen. Once Isaac's mother moves, her sprite also moves so much that she goes out of screen. Scenery ends up glitchy when camera moves. If you manage to get through the initial cutscenes somehow and control your character blindly so he can go to another screen, all of the above bugs happen, making the game completely unplayable. This seems to happen with both the english and japanese version and with both the original Golden Sun and its sequel (Golden Sun: The Lost Age). I haven't tested other versions but I think it's safe to assume it'll also happen with them.

### Steps to reproduce the behavior

Simply load any of the mentioned games and go through the initial naming screen. In TLA, there's also a little cutscene before that with images and text, which you can skip with Start.

### ROM details

Which games are affected by the issue: Golden Sun and Golden Sun: The Lost Age, both GBA games.

Which games, if any, are NOT affected by the issue: Every other game that I've tested.

### Option details

Video driver (simple, opengl or cairo): Simple and OpenGL

Sound driver (directsound, xaudio, openal, SDL): OpenAL and SDL.

### Build details

Operating System: Arch Linux with xorg 1.19.

Version of code (pre-built binary version, or commit ref, or just "master"): master

**Comment by Grumblesaur** [comment] 2017-11-12 19:57
I can reproduce the same issue on Ubuntu 17.10.

**Comment by Deukhoofd** [comment] 2017-12-11 01:00
I am encountering the exact same issue.

**Comment by RitaPena** [comment] 2018-03-19 19:49
Just tested this on my end and the glitch still occurs in both games on the latest version (2.0.2).

**Comment by rhenvar** [comment] 2018-04-02 07:12
same

**Comment by mattsan793** [comment] 2018-04-10 22:16
Ran into a similar issue with Mario Tennis Advance: Power Tour, running on Windows 10. As soon as you load into the game for character select, one of the characters walks off the screen. The other might appear and then vanish. After that it becomes hard to navigate past the opening setup, since you have to control one of the avatars just to select the letters for their name.

This seems like an issue that stretches across any GBA game made by Camelot. I also tried out Mario Golf Advance tour, and likewise the avatars in the opening sequence walk off the screen or don't appear at all.

**Comment by dhruvsus** [comment] 2018-05-26 08:33
I have been able to reproduce this issue in 18.04. Occurs in the both the ppa provided package and the build from source.

**Comment by Drazgul** [comment] 2018-06-16 05:06
.This is still happening on Golden Sun: the lost age. I have the latest VBA-M emulator and have tried at leat 3 different ROMs but can´t even go further the first dialog with Kraden, Alex and Jenna. Felix goes straight into the right wall and then everything else on the scene starts glitching completely.

**Comment by retro-wertz** [comment] 2018-06-16 05:08
@Drazgul latest from where? i dont think theres an already released based on recent updates, including the fix for this game. did you compile yourself from master branch?

**Comment by Drazgul** [comment] 2018-06-16 05:13
Downloaded from:
https://github.com/visualboyadvance-m/visualboyadvance-m/releases
64bitvba-m-Windows.7z
I assumed your last comment meant it was fixed:
"this should be fixed in latest commits"

My apologies if that is not the case. I do not program, just wanted to find any possible resolution.
 I am kinda glad it´s not my setup that´s glitching the game

**Comment by retro-wertz** [comment] 2018-06-16 05:19
ah ok. indeed thats an old version. a new update will be coming soon...

**Comment by retro-wertz** [comment] 2018-07-06 15:45
another Camelot game. this should be working in latest commit since this is what im playing atm.

**Closed** 2018-07-06 21:08 UTC
Labels: bug, fixed
