### ISSUE TITLE
VBA-M stuck at 800-900% speed

### ISSUE THREAD

**Issue by strydrehiryu** [visualboyadvance-m/visualboyadvance-m#859] opened 2021-07-28 10:33 UTC
***nightly not accessible for some reason. web page does not load***

### Expected behavior
Open VBA-M ~ open any ROM ~ play game normally at 100% speed on Simple setting (needed in order to stream)

### Actual behavior
Game automatically is at 900% speed or above, no matter the setting or ROM. Tried changing throttle to no avail no matter the percentage. Tried going into all other settings and even a factory reset but program is always at 900% speed or above

### Steps to reproduce the behavior
Open VBA-M, open ROM

### ROM details

Which games are affected by the issue (please state if GBA or GB game): GBA - All ROM's I currently have (over 20, tried them all, all stuck at over 900% speed)

Which games, if any, are NOT affected by the issue (please state if GBA or GB game): none

### Option details

Video driver (simple, opengl): simple

Sound driver (directsound, xaudio, openal, SDL): SDL

### Build details

Operating System (Windows, Mac, Linux (state distribution), etc.): Windows 10 Home
Processor: AMD Ryzen 7 3700X 8-Core Processor 3.59 GHz
RAM: 16 GB
64-bit OS, x64-based processor

**Comment by Squall-Leonhart** [comment] 2021-07-28 10:56
duplicate of #851

**Closed by Squall-Leonhart** 2021-07-28 10:56 UTC
