### ISSUE TITLE
Visual Boy Advanced not stopping to fast forward

### ISSUE THREAD

**Issue by Peterledgend** [visualboyadvance-m/visualboyadvance-m#828] opened 2021-03-28 13:07 UTC
Problem: My VisualBoyAdvance-M won't stop speeding up even when I reset the emulator or even when I reset my computer can someone help me with this issue and help me solve this problem
Rom Type: Game Boy Advance (All roms are being influenced so I don't think this is an issue with the rom)
Rom Name: Pokemon - Fire Red Version (U) (V1.1) (All roms are being influenced so I don't think this is an issue with the rom)
Operating system: Windows 10
Visual Boy Advance Version: 2.1.4

**Comment by Squall-Leonhart** [comment] 2021-03-28 13:29
Options > General > Throttle: 100%

Duplicate of #816

**Closed by Squall-Leonhart** 2021-03-28 13:29 UTC
