### ISSUE TITLE
Screensharing GB/GBC on 2.1.5 breaks the game

### ISSUE THREAD

**Issue by PowerPlayPone** [visualboyadvance-m/visualboyadvance-m#1140] opened 2023-06-05 17:40 UTC
### Expected behavior?

I expected to be able to show my friends (over Discord) a game I used to play in my youth: Yu-Gi-Oh! Dark Duel Stories.

### Actual behavior?

The moment I start a Discord screenshare, all hell breaks loose. The screen freaks out and won't show any input that the player does, even if the game registers said input.

### Steps to reproduce the problem

1. Boot up VBA-M 2.1.5
2. Start a Game Boy/Game Boy Color Game
3. Set up Discord Screenshare
4. Launch Screenshare
5. Prepare for an epilepsy warning because it'll happen on the user's end as well as anyone watching

### Error messages?

There is no error message to go alone with this because it's not technically something that would generate an error code.

However, trying to configure video DOES cause the emulator to hang and crash.

### What game were you playing

This issue may not be ROM-specific, but I was playing Yu-Gi-Oh! Dark Duel Stories at the time.

### What settings are you using?

I cannot access video settings on 2.1.5 without the emulator crashing, so I cannot readily provide most statistics.

### Specifications and Build details

VBA-M: 2.1.5-fda429fc
OS: Windows 10

Any settings beyond these should not matter for emulating a Game Boy title.

### Copyright Compliance

- [X] There are no infringing files attached to this bug report.

**Comment by ZachBacon** [comment] 2023-06-05 17:43
Are you trying to change the settings before sharing the screen or during sharing the screen?

**Comment by PowerPlayPone** [comment] 2023-06-05 18:40
It did that with the setting it came with. I turned off 'retain aspect ratio', 'bilinear filtering', 'transparent on-screen display'...

**Comment by Squall-Leonhart** [comment] 2023-06-05 22:47
Screensharing only works with the Simple video renderer, Duplicate of #767

**Closed by Squall-Leonhart** 2023-06-05 22:47 UTC
Labels: bug

**Comment by PowerPlayPone** [comment] 2023-06-06 21:17
I just tested that myself, yeah, I don't know why OpenGL breaks on screenshares. Thanks for your time.

**Comment by Squall-Leonhart** [comment] 2023-06-06 22:48
> I just tested that myself, yeah, I don't know why OpenGL breaks on screenshares. Thanks for your time.

Its a conflict between our implicit usage of OpenGL contexts and Discords hooking mechanism,  other tools have had similar issues but the developers of those tools accepted it as bug on their end and resolved it by improving their hooking mechanism.

My understanding is that with our current implicit implementation, when you hook vba-m with discord and it injects its streaming overlay, it hooks the wrong layer and writing the overlay into it corrupts presentation, Simple doesn't have this problem because it renders in the same context as the GUI itself.

A few changes are needed to migrate to a explicit opengl context, but the doing so is a bit above me so I've not managed to commit a fix at the present time.

**Comment by PowerPlayPone** [comment] 2023-06-22 22:27
Now I have a completely different issue: roughly 30 minutes to 1 hour after I start screensharing a GBA, GBC or GB game, my Discord client derps out and refreshes itself. I have no earthly idea what the hell is causing that but it's very infuriating when I'm showing my friends how I'm doing in a game.

**Comment by ZachBacon** [comment] 2023-06-22 22:56
This is most likely an unsolvable problem for now. But I do suggest installing obs-studio, from there you can do one of two options, use their virtual camera mode once you setup obs, or setup a preview pane and then tell discord to select that preview window, or use the virtual cam feed.

**Comment by PowerPlayPone** [comment] 2023-07-05 23:16
As well, it seems controller background input has broken.

**Comment by Squall-Leonhart** [comment] 2023-07-06 04:46
Try this
[visualboyadvance-m.zip](https://github.com/visualboyadvance-m/visualboyadvance-m/files/11964207/visualboyadvance-m.zip)
