### ISSUE TITLE
white screen on windows 10 vm

### ISSUE THREAD

**Issue by Trinsdar** [visualboyadvance-m/visualboyadvance-m#607] opened 2020-02-14 03:02 UTC
### Expected behavior
It displays the loaded game
### Actual behavior
Sounds play, but the game screen stays white
### Steps to reproduce the behavior
Install windows 10 on a vm.
Download vba-m in the vm.
Open a gba rom in vba-m.
This might happen in a fresh windows 10 install too, but i can't really test that.
### ROM details

Which games are affected by the issue (please state if GBA or GB game):
So far i've done pokemon emerald and firered, it's not the roms cause they work fine on the snap vba-m version. I'm going to guess it affects all gba roms at least, haven't tried gbc or gb.

Which games, if any, are NOT affected by the issue (please state if GBA or GB game):
None so far

Include screenshots of ROM Information (File > ROM Information):
https://imgur.com/qULMbP1
If you are using a BIOS file, please say which one.

### Option details

Video driver (simple, opengl): opengl

Sound driver (directsound, xaudio, openal, SDL): sdl

### Build details

Operating System (Windows, Mac, Linux (state distribution), etc.):
Windows 10 on oracle virtual bix, host os is Ubuntu 19.10, xorg(don't think the host os is relevant, but mentioning it anyways).

Version of code (pre-built binary version, or commit ref, or just "master"): 2.1.4

The vm video driver is VirtualBox Graphics Adapter

### Hardware details:

If relevant, the joystick you are using and the drivers you are using for it: n/a

**Comment by denisfa** [comment] 2020-02-14 03:23
@Trinsdar Thank you for the report. Can you confirm if `OpenGL` is functional on the vm? 

If you use `Simple` video driver, it should work.

**Comment by ZachBacon** [comment] 2020-02-14 08:43
One question though I have to ask, why load vba-m in a virtual machine @Trinsdar?

**Comment by Trinsdar** [comment] 2020-02-14 16:50
It's mainly just for convenience, i don't have to drag the rom i'm hacking over to the shared folder i setup every time I make a change and want to test it.

**Comment by ZachBacon** [comment] 2020-02-14 23:12
@Trinsdar fair enough, I know from experience sometimes opengl doesn't quite work well with vm's, well virtualbox anyways, not so sure for others. But I understand the use case, I do suggest the simple driver though, I think our opengl implementation needs to be flushed out better, kinda uses wxwidgets implementation which I think needs to be redone for our use case for better compatibility in this case.

**Comment by rkitover** [comment] 2020-02-24 21:33
Closing this as the issue is stalled.

**Closed by rkitover** 2020-02-24 21:33 UTC
Labels: no reply from requestor, question

**Comment by Trinsdar** [comment] 2020-02-26 21:06
oh sorry for not replying, forgot about this. simple works.

**Comment by rkitover** [comment] 2020-02-26 23:31
That's all good, we're just trying to keep things tidy with the labels, thank you for getting back to us!
