### ISSUE TITLE
Wrong colors in Metroid Fusion

### ISSUE THREAD

**Issue by albertsl** [visualboyadvance-m/visualboyadvance-m#670] opened 2020-05-20 17:41 UTC
I first played the game with Visual Boy Advance and could complete the game with no problem. When using VBA-m, I can't jump making the game unplayable.

### Expected behavior
Samus jumping when A is pressed

### Actual behavior
Samus does a weird movement but doesn't jump

### Steps to reproduce the behavior
Open the game, advance the intro history, move and try to jump

### ROM details

Which games are affected by the issue (please state if GBA or GB game):
Metroid Fusion, I can share the exact ROM I used if needed.

Include screenshots of ROM Information (File > ROM Information):
![imagen](https://user-images.githubusercontent.com/7349234/82478737-a24cb580-9ad1-11ea-8db6-783e32af1ccb.png)

### Option details

Video driver (simple, opengl):
OpenGL

Sound driver (directsound, xaudio, openal, SDL):
SDL

### Build details

Operating System (Windows, Mac, Linux (state distribution), etc.):
Windows 10

Version of code (pre-built binary version, or commit ref, or just "master"):
Visual Boy Advance-M 2.1.4

**Comment by denisfa** [comment] 2020-05-20 17:58
> Samus does a weird movement but doesn't jump

@albertsl What weird movement, exactly? If you can, please check the latest nightly build available as well. Are you using a keyboard or a joystick?

I recorded a video while playing the game (keyboard). I can jump ok. One thing I noticed is that if I spam the jump button, I don't do a full jump in game (final part).

[Metroid Fusion (USA, Australia).avi.zip](https://github.com/visualboyadvance-m/visualboyadvance-m/files/4658519/Metroid.Fusion.USA.Australia.avi.zip)

**Comment by albertsl** [comment] 2020-05-20 20:59
Hi, thank you for your reply!
I tested with the nightly build and the jump worked fine however I had a problem with the colors, they don't seem the right colors, here is a screenshot. The colors are right in your video.
![imagen](https://user-images.githubusercontent.com/7349234/82496340-d84b6300-9aec-11ea-9613-bb130c20ff5c.png)

Then I opened it with the version I reported earlier and had no issue with jumping. I don't know if configuration is shared between different executables (they were in different folders) but if that's the case then this is probably a problem with configuration on my part.

When I had the issue I tested with both the keyboard and a gamepad and had the same problem with both.

**Comment by denisfa** [comment] 2020-05-22 19:45
@albertsl Thank you for the feedback! I will take a look at this.

> I tested with the nightly build and the jump worked fine however I had a problem with the colors, they don't seem the right colors, here is a screenshot. The colors are right in your video.

That is very weird, as nothing was changed for this; could you check if it is not a filter or something from the configuration? Try recording a video and see if it matches what you are seeing. Were the colors correct when you dealt with the jumping issue?

> Then I opened it with the version I reported earlier and had no issue with jumping. I don't know if  configuration is shared between different executables (they were in different folders) but if that's the case then this is probably a problem with configuration on my part.
> When I had the issue I tested with both the keyboard and a gamepad and had the same problem with both.

If there is a `vbam.ini` in the same folder of the exe, we use it. Otherwise, we use `%LOCALAPPDATA%/visualboyadvance-m/vbam.ini`. If you still have the problematic config, please attach here so I can examine.

**Comment by albertsl** [comment] 2020-05-23 10:15
I checked and I'm using the same configuration for both the nightly build and the stable release, the one located in LOCALAPPDATA and using this exact same configuration I get the colors right on the stable and wrong on the nightly.

I tried changing the pixel filter many times but it doesn't change anything and on the nightly there is some problem when changing, there appears a text that says "No support for wglGetExtensionsString".

This is the configuration file:

> [Display]
Bilinear=1
Filter=simple3x
FilterPlugin=
IFB=none
KeepOnTop=0
MaxThreads=1
RenderMethod=opengl
Scale=3
Stretch=1
[GB]
BiosFile=
GBCBiosFile=
GBCROMDir=
PrintAutoPage=1
PrintScreenCap=0
ROMDir=
Palette0=7FFF,56B5,318C,0000,7FFF,56B5,318C,0000
Palette1=7FFF,56B5,318C,0000,7FFF,56B5,318C,0000
Palette2=7FFF,56B5,318C,0000,7FFF,56B5,318C,0000
ColorOption=0
LCDFilter=0
[GBA]
BiosFile=
LinkAuto=0
LinkFast=0
LinkHost=127.0.0.1
LinkProto=0
LinkTimeout=500
LinkType=0
ROMDir=
LCDFilter=1
LinkPort=5738
ServerIP=*
[General]
AutoLoadLastState=0
BatteryDir=
FreezeRecent=0
RecordingDir=
RewindInterval=0
ScreenshotDir=
StateDir=
StatusBar=0
[Joypad]
AutofireThrottle=1
Default=1
[Joypad/1]
Up=W,Joy1-Hat0N,Joy1-Axis1-,W,Joy1-Hat0N,Joy1-Axis1-,Joy1-Button11
Down=S,Joy1-Hat0S,Joy1-Axis1+,S,Joy1-Hat0S,Joy1-Axis1+,Joy1-Button12
Left=A,Joy1-Hat0W,Joy1-Axis0-,A,Joy1-Hat0W,Joy1-Axis0-,Joy1-Button13
Right=D,Joy1-Hat0E,Joy1-Axis0+,D,Joy1-Hat0E,Joy1-Axis0+,Joy1-Button14
A=L,Joy1-Button0,L,Joy1-Button0,Joy1-Button0,Joy1-Button0
B=K,Joy1-Button1,K,Joy1-Button1,Joy1-Button1,Joy1-Button1
L=I,Joy1-Button4,I,Joy1-Button4,Joy1-Button4,Joy1-Button9
R=O,Joy1-Button5,O,Joy1-Button5,Joy1-Button5,Joy1-Button10
Select=BACK,Joy1-Button6,BACK,Joy1-Button6,Joy1-Button4
Start=ENTER,Joy1-Button7,ENTER,Joy1-Button7,Joy1-Button6
MotionUp=
MotionDown=
MotionLeft=
MotionRight=
MotionIn=
MotionOut=
AutoA=
AutoB=
Speed=SPACE,SPACE,Joy1-Button2
Capture=
GS=
[Joypad/2]
Up=
Down=
Left=
Right=
A=
B=
L=
R=
Select=
Start=
MotionUp=
MotionDown=
MotionLeft=
MotionRight=
MotionIn=
MotionOut=
AutoA=
AutoB=
Speed=
Capture=
GS=
[Joypad/3]
Up=
Down=
Left=
Right=
A=
B=
L=
R=
Select=
Start=
MotionUp=
MotionDown=
MotionLeft=
MotionRight=
MotionIn=
MotionOut=
AutoA=
AutoB=
Speed=
Capture=
GS=
[Joypad/4]
Up=
Down=
Left=
Right=
A=
B=
L=
R=
Select=
Start=
MotionUp=
MotionDown=
MotionLeft=
MotionRight=
MotionIn=
MotionOut=
AutoA=
AutoB=
Speed=
Capture=
GS=
[Sound]
AudioAPI=sdl
AudioDevice=
Buffers=10
Enable=783
GBAFiltering=50
GBAInterpolation=1
GBDeclicking=1
GBEcho=20
GBEnableEffects=0
GBStereo=15
GBSurround=0
Quality=44
Volume=100
[geometry]
fullScreen=0
isMaximized=1
windowHeight=581
windowWidth=736
windowX=182
windowY=212
[preferences]
LinkNumPlayers=2
agbPrint=0
autoFrameSkip=0
autoPatch=1
autoSaveCheatList=1
borderAutomatic=0
borderOn=0
captureFormat=0
cheatsEnabled=0
disableStatus=0
emulatorType=4
flashSize=0
frameSkip=0
fsColorDepth=32
fsFrequency=60
fsHeight=600
fsWidth=800
gbPaletteOption=0
gbPrinter=0
gdbBreakOnLoad=0
gdbPort=55555
maxScale=0
pauseWhenInactive=1
rtcEnabled=0
saveType=0
showSpeed=0
showSpeedTransparent=1
skipBios=0
skipSaveGameBattery=0
skipSaveGameCheats=0
speedupFrameSkip=9
speedupThrottle=0
throttle=100
useBiosGB=0
useBiosGBA=0
useBiosGBC=0
vsync=0
speedupThrottleFrameSkip=1
[Recent]
file1=C:\\Users\\Albert\\Downloads\\tmp\\Metroid Fusion (USA).gba
file2=C:\\Users\\Albert\\Downloads\\0Games\\Golden Sun (Spain).gba
file3=C:\\Users\\Albert\\Downloads\\0Games\\Golden Sun (Spain)\\Golden Sun (Spain).gba
file4=C:\\Users\\Albert\\Downloads\\Metroid Fusion (USA).gba
file5=C:\\Users\\Albert\\Downloads\\pokemon_esmeralda_esp.gba
file6=C:\\Users\\Albert\\Downloads\\Golden Sun (Spain).gba
file7=C:\\Users\\Albert\\Downloads\\Golden Sun (Spain)\\Golden Sun (Spain).gba
file8=
file9=
file10=
[ui]
hideMenuBar=1


For the jump error, I deleted the configuration file to create a new one with the default parameters of the stable release and the jump worked fine. Then I searched the options and found out that activating Autofire A the weird jump was happening again. So maybe that's the configuration I had wrong.

**Comment by rkitover** [comment] 2020-06-02 00:08
@denisfa this is probably related to the lcd filter stuff, I will take a look if I can reproduce.

Which colors are actually "correct" in this case?

**Comment by denisfa** [comment] 2020-06-17 16:11
Sorry about the delay, I forgot about this. The color difference reason is that on nightly we
have added an option `Options` > `Game Boy Advance` > `LCD Filter` ticked by default. If you
use the nightly, just toggle this option and it should be the same colors as the latest stable.

Keep in mind that unknown options (such as `LCD Filter`, for the stable) are deleted. So if you
toggle it off with nightly, open the stable and then use nightly again the filter will be active, since
it is by default (the stable will erase the config for `LCD Filter`).

I will close this now. Feel free to reopen if necessary.

**Closed by denisfa** 2020-06-17 16:11 UTC
Labels: UI, UI Win, gba core

**Comment by rkitover** [comment] 2020-06-18 01:10
@denisfa That's what I thought, can you please verify that in his screenshot above, with the LCD filter active, the colors are the intended colors, that is, they are similar to the original hardware, that's all I wanted to know.
