### ISSUE TITLE
Emu not pulling bios file location from ini

### ISSUE THREAD

**Issue by RetroAsylum79** [visualboyadvance-m/visualboyadvance-m#187] opened 2018-01-31 23:59 UTC
### Expected behavior
bios paths stored in path location field
### Actual behavior
Saves Bios paths to ini, but isn't loading them upon emulator load, thus causing crashes when "use bios" is enabled for gb, gbc. 
### Steps to reproduce the behavior
Set bios file locations for both gb and gbc, tick use GB BIOS and GBC BIOS options, close emulator and try loading a rom. It should crash the program. GBA bios location also not loading from ini, however message "Can't load BIOS" shows but still loads game without crashing.
### Crash bugs

If this is a crash bug, and you have the time and inclination, please provide a
symblic backtrace.

Instructions for doing so are
[here](https://github.com/visualboyadvance-m/visualboyadvance-m/blob/master/README.md#reporting-crash-bugs).

### ROM details

Which games are affected by the issue (please state if GBA or GB game):
Random
Which games, if any, are NOT affected by the issue (please state if GBA or GB game):

### Option details

Video driver (simple, opengl):
simple
Sound driver (directsound, xaudio, openal, SDL):
default
### Build details

Operating System (Windows, Mac, Linux (state distribution), etc.):
Windows 10
If using Linux, specify if using xorg or Wayland:

Version of code (pre-built binary version, or commit ref, or just "master"):
2.0.1
### Hardware details:

If your joystick or gamepad isn't working in Linux, please try to troubleshoot
using the information on this page:
https://wiki.archlinux.org/index.php/Gamepad **BEFORE** filing an issue. We use
SDL for joystick support, any problems will generally be an issue with SDL and
**NOT** the emulator.

If relevant, the joystick you are using and the drivers you are using for it:

**Comment by ZachBacon** [comment] 2018-02-01 01:38
Known issue, duplicate of several we have in the bug tracker. It's going to be fixed as soon as I'm able to get more time (job hasn't been too kind to me as of late)

**Closed** 2018-02-01 01:39 UTC
Labels: duplicate
