### ISSUE TITLE
Please get cheats (gameshark?) working

### ISSUE THREAD

**Issue by metalmight** [visualboyadvance-m/visualboyadvance-m#85] opened 2017-02-23 20:02 UTC
### Expected behavior
Cheats work
### Actual behavior
Cheats don't work
### Steps to reproduce the behavior
Try to use cheats
### Build details
2.0.0 beta 2
Operating System (Windows, Mac, Linux, etc.):
Windows 10
Interface (wx, SDL, default is wx):
Win32 - MFC
Version of code (pre-built binary version, or commit ref, or just "master"):
I don't know
Any other relevant build information:

If this is e.g. a joystick or video issue, then the relevant hardware information:

**Comment by ZachBacon** [comment] 2017-02-23 20:04
Mfc is unsupported anymore.
Also download https://github.com/visualboyadvance-m/visualboyadvance-m/releases/tag/Keyboardfixes
And see what happens.

**Comment by metalmight** [comment] 2017-02-23 20:49
Ok great.  I got cheats working in 2.0.0-beta 2 WX; but there are things I disliked about this version such as a choppy frame-rate and a controller issue.

**Comment by ZachBacon** [comment] 2017-02-23 20:54
We dropped the mfc one due to not making sense to have multiple interfaces, the wxwidgets one allows us to provide one interface across multiple platforms. Anyways the download URL contains a lot of fixes that the old 2.0 bet 2 didn't have.

**Comment by rkitover** [comment] 2017-02-28 22:28
Ok so if cheats work in the Wx builds I will close this, please feel free to file issues related to the Wx build separately.

**Comment by metalmight** [comment] 2017-02-28 22:31
I still can't get cheats working in the latest version.  I tried both x86_64 and i686 versions.

**Comment by rkitover** [comment] 2017-02-28 22:36
In that case, reopening.

**Comment by rkitover** [comment] 2017-02-28 22:53
@metalmight can you please clarify what you mean by 'cheats not working', what have you tried to do and what you expected to happen. Zach says he is almost certain cheats are working fine.

**Comment by metalmight** [comment] 2017-03-02 20:47
I entered cheat codes for Metroid Fusion and they didn't work.  They work fine in the original VBA so i'm using that for now.

**Comment by ZachBacon** [comment] 2017-03-03 03:16
So I did some investigation. Cheats do work, BUT, there are other cheats that don't for said game for the US region.

**Comment by ZachBacon** [comment] 2017-03-03 03:16
I'll be investigating this further and track down causes

**Comment by metalmight** [comment] 2017-03-03 08:08
I'll post the codes in case in helps.
Enable Codes:
00000F6D 000A
100008B4 0007
Infinite Health:
83001310 0833

As I said they work fine in the original VBA, so I know they are working codes.  I am using the USA version of the game.

**Comment by Dacemorden** [comment] 2017-05-05 18:13
Hi, um, I'm using a mac os 10.12.4, and I'm using the visual boy advance -m from this link
https://sourceforge.net/projects/vbam/files/OSX-Wx/visualboyadvance-m.zip/download
and I'm trying to use cheats on Mega Man Battle Network 6 Gregar...All I need is one cheat, and that's the complete library cheat. (The master code to allow the cheat and the cheat itself)-gameshark

Master Code
930CFE0E61A7
5E4E1F94523A
CB3A64B69A02

Complete Library+PA
024231FCC812
23A319CC8070
2B4B75D852C6
024231FCC812
D8B888060A34
2B4B75D852C6
024231FCC812
B9D9482FA7BA
1200F539DA87

I'm not sure how it works on mac, 
I checked the enable cheats and I go to list cheats
Click the green button then, fill in the spaces
![master](https://cloud.githubusercontent.com/assets/28454029/25758297/fb5393d0-319b-11e7-810e-eeb1c34f157e.png)
is it normal for all of the code to be separated like that?
![list](https://cloud.githubusercontent.com/assets/28454029/25758345/36c0e224-319c-11e7-804d-dda48ebc5240.png)
I just copy and pasted it in, and do the same for the actual code
![list2](https://cloud.githubusercontent.com/assets/28454029/25758404/79908294-319c-11e7-8148-baa0f430ac0c.png)
but uh its not 200/200
![screen shot 2017-05-05 at 2 09 59 pm](https://cloud.githubusercontent.com/assets/28454029/25758437/9346ed2c-319c-11e7-8cd2-54df7dd95115.png)
am I doing something wrong? anything would help

(ps: if it ends up unresolvable, if someone has the ability to get that code working, could you just make a save file in the beginning of the game with the complete library? I've beaten this game and the series 3 or more times now and I just want to get pass the door that requires the mark s.)

Thank you in advance!

**Comment by ZachBacon** [comment] 2017-05-05 18:15
We don't use sourceforge for downloads anymore.

**Comment by ZachBacon** [comment] 2017-05-05 18:22
Also this issue is a duplicate of one someone posted before that we are already investigating

**Comment by hoover1979** [comment] 2017-07-02 13:01
VBA has working cheats.  VBA-M does not.  is this ever going to be fixed as the latest download I can find is from 2016.  I like VBA-M for 6xBRZ filtering and aspect correct fullscreen.  But the cheat system in the emulator is not working no matter what I try.

**Comment by noabody** [comment] 2017-07-16 20:23
Somehow, when I use these older version of the program, they are able to create working cheats:

https://sourceforge.net/projects/vbam/files/Win32%20-%20MFC/VisualBoyAdvance-M-2.0.0-beta2.7z/download 
https://sourceforge.net/projects/vbam/files/Win32-Wx/VisualBoyAdvance-M-WX-2.0.0-beta2.7z/download

The CodeBreaker cheats I added and saved to a .clt file work in both the older and latest versions VBA-M.

Looking at the .clt file with HxD I can see the line terminations are different but don't know what impact that has.  New versions of VBA-M carry the code and name along with FF FF FF FF (as a line termination?).  Old versions store a whole lot more information which must describe something to do with the codes.

Example:
Final Fantasy Dawn of Souls AGP-BFFE-USA:
No Random
42001A180000
000000020002

.clt (not-working):
`................ÿÿÿÿ........................42001A18 0000.......No Random.dom.......................ÿÿÿÿ........................00000002 0002.......No Random.dom.......................`
![cltnotworking](https://user-images.githubusercontent.com/29848078/28250966-2703694c-6a31-11e7-927f-0bc4f86b2cd9.png)

.clt (working)
`...............................B............42001A18 0000.......No Random.dom.......................ÿÿÿÿ........................00000002 0002.......No Random.dom...................................ì'.Bì'..........`
![cltworking](https://user-images.githubusercontent.com/29848078/28250968-2ffc050e-6a31-11e7-94c3-aeaca8d66e32.png)

I'm explicitly adding the cheats as "codebreaker [CB]" in every case.  What I find unusual is that I'm inputting the codes in exactly the same way across the different versions of VBA-M.  Copying and pasting a multi-line code in the latest version just doesn't work.  But in that very same version, it will happily import the .clt file created with the older version and that actually does work.

There isn't a problem with the cheat engine itself but input processing through the GUI and not from a loaded .clt file.

**Comment by Squall-Leonhart** [comment] 2023-07-15 06:13
I cant replicate this at this point.

**Closed by Squall-Leonhart** 2023-07-15 06:13 UTC
Labels: bug, duplicate, enhancement
