### ISSUE TITLE
[Feature request]: Rework Motionhandling

### ISSUE THREAD

**Issue by GrEgStAr3000** [visualboyadvance-m/visualboyadvance-m#1211] opened 2024-01-01 05:31 UTC
### Request box

Requesting a complete Re-Work of the framehandling with the upcoming Release/Build of VBA-M to bring back the fluent´n smooth motion from former VBA 1.8.0. Seeing how beautifully AND stable 1.8.0. handled the videosynchronazation with it´s smooth 60hz-like Feeling brought me personally right back to the old Release.

### Reason box

The way the new VBA-M release is handling the frames ( in comparison to the old 1.8.0 - Build ) is a massiv downgrade. Having booting up both versions at the same time, clearly shows a huge difference in speed and smooth motion. It just feels like having the Frame-Skip option enabled. . . With 1.8.0 I just had to set Frame skip to ,, 0 ,, and it worked perfect.

### Examples

Changed different options. VSync - on/off, made sure ( NOT to ) check ,,Auto skip frames,, , used different Output modules, Turned on/off Filters and even tried to fondle around with the Frame Speed-Up option. It´s no good.

**Comment by Squall-Leonhart** [comment] 2024-01-01 05:45
Request denied, find the issue in your computer and resolve it.

**Comment by GrEgStAr3000** [comment] 2024-01-01 06:00
Wow, that is rich. . . Seeing how you people came up with Ver- 2.1.8 and STILL not having realized how bad your so called OpenGl/Simple - Renderer works is just a joke. I´m going back to 1.8.0. Screw this half backed thing.

**Comment by rkitover** [comment] 2024-01-01 08:37
Just out of curiosity, can you try changing your sound driver to DirectSound and see if it solves your issue?

**Comment by rkitover** [comment] 2024-01-01 08:41
Also make sure you aren't using the debug build, the debug build is very slow.

**Comment by GrEgStAr3000** [comment] 2024-01-01 08:55
What in tarnation?! Ó__ò How in god´s name is or was this related to the slowdonw?! It. . . It seems to have worked. =OOO

**Comment by Squall-Leonhart** [comment] 2024-01-01 09:57
Theres a bug in SDL2's resampler, the audio can race a head throwing the audio throttle code ahead and cause the appearance of a windback periodically.

https://github.com/libsdl-org/SDL/issues/6326

**Comment by rkitover** [comment] 2024-01-01 13:33
Duplicate of #709

**Closed** 2024-01-01 13:33 UTC
Labels: enhancement
