### ISSUE TITLE
Windows build executable missing dll error

### ISSUE THREAD

**Issue by Adelynn** [visualboyadvance-m/visualboyadvance-m#254] opened 2018-06-13 17:11 UTC
### Expected behavior
Executable built on Windows runs fine
### Actual behavior
Gives missing DLL error when trying to run it. 
Maybe I'm doing something wrong (I am a bit new to this), but building it on Linux Mint x64 and running it on Windows gave me no issues at all.
![2018-06-13_12-09-10](https://user-images.githubusercontent.com/36391156/41366722-a08d1fe8-6f02-11e8-9233-55a62b6f794e.png)

### Steps to reproduce the behavior
Build on Windows, run the file.
### Crash bugs

If this is a crash bug, and you have the time and inclination, please provide a
symblic backtrace.

Instructions for doing so are
[here](https://github.com/visualboyadvance-m/visualboyadvance-m/blob/master/README.md#reporting-crash-bugs).

### ROM details

Which games are affected by the issue (please state if GBA or GB game):

Which games, if any, are NOT affected by the issue (please state if GBA or GB game):

### Option details

Video driver (simple, opengl):

Sound driver (directsound, xaudio, openal, SDL):

### Build details

Operating System (Windows, Mac, Linux (state distribution), etc.): Same thing happens on both Windows 7 32 bit and Windows 10 64 bit

If using Linux, specify if using xorg or Wayland:

Version of code (pre-built binary version, or commit ref, or just "master"): master

### Hardware details:

If your joystick or gamepad isn't working in Linux, please try to troubleshoot
using the information on this page:
https://wiki.archlinux.org/index.php/Gamepad **BEFORE** filing an issue. We use
SDL for joystick support, any problems will generally be an issue with SDL and
**NOT** the emulator.

If relevant, the joystick you are using and the drivers you are using for it:

**Comment by ZachBacon** [comment] 2018-06-13 17:14
So what you need to do is go to your compilers bin folder, usually /usr/x86_64-w64-mingw32/bin (if compiled against 64bit) or /usr/i686-w64-mingw32/bin and copy the dolphin from there.

**Comment by ZachBacon** [comment] 2018-06-14 12:30
closing issue because not a bug

**Closed by ZachBacon** 2018-06-14 12:30 UTC
