### ISSUE TITLE
fail compiling on mac

### ISSUE THREAD

**Issue by 3ace** [visualboyadvance-m/visualboyadvance-m#96] opened 2017-03-12 02:37 UTC
I'm using MacOS Sierra, previously I'm using build that posted in the [forum here](http://vba-m.com/forum/thread-1568-post-6710.html#pid6710) and it worked fine.

Bu then I tried to install latest update by using release build from [Release](https://github.com/visualboyadvance-m/visualboyadvance-m/releases) page but mac said they are damaged and cannot be opened.

Then I've tried checking out from master branch to build it using the instruction provided but it failed when executing "make -j8"

> [ 10%] Built target wxvbam_translations
> [ 10%] Building C object fex/CMakeFiles/fex.dir/7z_C/7zAlloc.c.o
> [ 11%] Building C object fex/CMakeFiles/fex.dir/7z_C/7zCrcOpt.c.o
> [ 13%] Building C object fex/CMakeFiles/fex.dir/7z_C/7zIn.c.o
> [ 13%] Building C object fex/CMakeFiles/fex.dir/7z_C/7zStream.c.o
> [ 13%] Building C object fex/CMakeFiles/fex.dir/7z_C/7zDec.c.o
> [ 14%] Building C object fex/CMakeFiles/fex.dir/7z_C/7zBuf.c.o
> clangclang: : errorerror: : unsupported option '--param ssp-buffer-size=4'unsupported option '--param ssp-buffer-size=4'
> 
> clang: error: unsupported option '--param ssp-buffer-size=4'
> clang: error: unsupported option '--param ssp-buffer-size=4'
> clang: error: unsupported option '--param ssp-buffer-size=4'
> clang: error: unsupported option '--param ssp-buffer-size=4'
> make[2]: *** [fex/CMakeFiles/fex.dir/7z_C/7zDec.c.o] Error 1
> make[2]: *** Waiting for unfinished jobs....
> make[2]: *** [fex/CMakeFiles/fex.dir/7z_C/7zAlloc.c.o] Error 1
> make[2]: *** [fex/CMakeFiles/fex.dir/7z_C/7zIn.c.o] Error 1
> make[2]: *** [fex/CMakeFiles/fex.dir/7z_C/7zStream.c.o] Error 1
> make[2]: *** [fex/CMakeFiles/fex.dir/7z_C/7zBuf.c.o] Error 1
> make[2]: *** [fex/CMakeFiles/fex.dir/7z_C/7zCrcOpt.c.o] Error 1
> [ 16%] Building C object fex/CMakeFiles/fex.dir/7z_C/7zCrc.c.o
> [ 16%] Building CXX object CMakeFiles/vbamcore.dir/src/common/ConfigManager.cpp.o
> [ 16%] Building C object CMakeFiles/vbamcore.dir/src/common/dictionary.c.o
> [ 17%] Building CXX object CMakeFiles/vbamcore.dir/src/common/Patch.cpp.o
> [ 18%] Building C object CMakeFiles/vbamcore.dir/src/common/iniparser.c.o
> clang: error: unsupported option '--param ssp-buffer-size=4'
> [ 18%] Building C object CMakeFiles/vbamcore.dir/src/common/memgzio.c.o
> make[2]: *** [fex/CMakeFiles/fex.dir/7z_C/7zCrc.c.o] Error 1
> make[1]: *** [fex/CMakeFiles/fex.dir/all] Error 2
> make[1]: *** Waiting for unfinished jobs....
> clang: error: unsupported option '--param ssp-buffer-size=4'
> make[2]: *** [CMakeFiles/vbamcore.dir/src/common/Patch.cpp.o] Error 1
> make[2]: *** Waiting for unfinished jobs....
> clang: error: unsupported option '--param ssp-buffer-size=4'
> clang: error: unsupported option '--param ssp-buffer-size=4'
> make[2]: *** [CMakeFiles/vbamcore.dir/src/common/memgzio.c.o] Error 1
> make[2]: *** [CMakeFiles/vbamcore.dir/src/common/iniparser.c.o] Error 1
> clang: error: unsupported option '--param ssp-buffer-size=4'
> make[2]: *** [CMakeFiles/vbamcore.dir/src/common/dictionary.c.o] Error 1
> clang: error: unsupported option '--param ssp-buffer-size=4'
> make[2]: *** [CMakeFiles/vbamcore.dir/src/common/ConfigManager.cpp.o] Error 1
> [ 19%] Building CXX object CMakeFiles/vbamcore.dir/src/Util.cpp.o
> clang: error: unsupported option '--param ssp-buffer-size=4'
> make[2]: *** [CMakeFiles/vbamcore.dir/src/Util.cpp.o] Error 1
> make[1]: *** [CMakeFiles/vbamcore.dir/all] Error 2
> make: *** [all] Error 2

is there any step that I've missed? should I install any dependencies by myself? didn't all the dependencies has been handled by "installdeps" script?

**Comment by ZachBacon** [comment] 2017-03-12 02:39
The issue is that clang doesn't support gcc's stack smashing protector it seems. I'll talk to rkitover to change the detection behaviour.

**Comment by ZachBacon** [comment] 2017-03-12 03:24
Rkitover fixed it in master, do a git pull and it should work for you now.

**Comment by 3ace** [comment] 2017-03-12 08:56
thanks, I've successfully build the app

**Comment by ZachBacon** [comment] 2017-03-12 13:23
Closing issue and thanks for reporting the issue

**Closed by ZachBacon** 2017-03-12 13:23 UTC
Labels: bug, fixed
