### ISSUE TITLE
[Bug]: Keyboard does not working

### ISSUE THREAD

**Issue by olorinvicxD** [visualboyadvance-m/visualboyadvance-m#1076] opened 2023-02-11 21:46 UTC
### Expected behavior?

Keyboards responding accordingly to setup (input menu).

### Actual behavior?

Keyboard is not working. Autorun function does work. However, the app just don't run keyboard options. I've already changed input options (options > input > configure) but, when de rom is running, it doesnt work... I've read the information about SDL indicated in "If your joystick or gamepad isn't working in Linux"... however Im new in Linux and it didnt help a lot. But I believe that is something related to SDL. I have installed SDL2. Im running in Ubuntu 22.04

### Steps to reproduce the problem

1. Intsall VBA-A from official website for linux in Ubuntu 22.04
2. Open any rom
3.Try to play according input setup
4.
5.
...

### What game were you playing

Any of pokemon franchise

### What settings are you using?

Video driver (simple, opengl):
Sound driver (directsound, xaudio, openal, SDL):
Scale Filter Used?:

### Specifications and Build details

VBA-M: (include commit version number and whether you are using the 32-bit or 64-bit version)
OS: Ubuntu 22.04
If using Linux, specify if using xorg or Wayland: oh, I dont know this...
CPU: 
GPU:
RAM: 8g

### Copyright Compliance

- [X] There are no infringing files attached to this bug report.

**Comment by Steelskin** [comment] 2023-02-11 21:51
Could you point us to where you downloaded / installed VBA-m?

I suspect you're using a snap but I'd like to make sure. @ZachBacon you mentioned some issues with gamepad input in the snap IIRC

**Comment by olorinvicxD** [comment] 2023-02-11 21:55
I downloaded via terminal, using sudo snap install visualboyadvance-m --beta
I think it is in snap folder as usual..

Not sure if I answered the question...

**Comment by ZachBacon** [comment] 2023-02-11 21:59
Yeah right now the snaps have a joystick issue I'm trying to debug currently. I have no eta on when it'll be fixed, so right now the issue is known, no workaround, you'll have to be patient until I can resolve it.

**Comment by olorinvicxD** [comment] 2023-02-11 22:06
Thanks! I'll track the news... i hope sucess in resolution

**Comment by Squall-Leonhart** [comment] 2023-02-12 00:55
https://github.com/standardnotes/forum/issues/1105

**Comment by Squall-Leonhart** [comment] 2023-02-12 00:57
This is an ubuntu 22.04 issue.

**Comment by ZachBacon** [comment] 2023-02-12 01:13
Except the current snap isn't built against core22

**Comment by ZachBacon** [comment] 2023-02-12 01:14
Iirc the current snap that's version 2.1.4 is built against core18

**Comment by Squall-Leonhart** [comment] 2023-02-12 01:22
@olorinvicxD  can you post the snap logs?

**Comment by Erik-vdb** [comment] 2023-05-16 16:10
Same happening for me though I installed it from GNOME Software Store (Nobara 37)

**Comment by joshuahackbarthsoftware** [comment] 2023-09-21 00:26
Has this been fixed yet?

**Comment by ZachBacon** [comment] 2023-09-21 00:36
Try it for yourself.

**Comment by fink1369** [comment] 2023-10-02 01:14
when i open visualboyadvance linux, none of my keyboard buttons work, i.e. ENTER  should be START, but when i press, it doesn't respond, same with all keyboard/GBAbutton input. Is this same as what is being discussed here?

**Comment by SAnthonyH** [comment] 2023-10-02 22:27
> when i open visualboyadvance linux, none of my keyboard buttons work, i.e. ENTER should be START, but when i press, it doesn't respond, same with all keyboard/GBAbutton input. Is this same as what is being discussed here?

Having the exact same issue, does anyone know if its fixed yet? Might have to find a better alternative if no one is working on it

**Comment by yuripinto** [comment] 2023-10-27 19:49
I'm having this same issue in Ubuntu 22.04 (installed using snap). I'm getting this error in terminal: 

`(visualboyadvance-m:17475): GLib-GIO-WARNING **: 16:42:59.438: Error creating IO channel for /proc/self/mountinfo: Permission denied (g-file-error-quark, 2)
`

When I try to run with sudo (trying to evaluate any permission error), I get this another one:

`mkdir: cannot create directory '/run/user/0': Permission denied
Authorization required, but no authorization protocol specified
Unable to init server: Could not connect: Connection refused
16:43:28: Error: Unable to initialize GTK+, is DISPLAY set properly?
`

Is anyone receiving this same error message?

**Comment by Squall-Leonhart** [comment] 2023-10-27 23:51
That is not the "same" issue.

**Comment by yuripinto** [comment] 2023-10-28 02:08
Exactly the same issue reported by @olorinvicxD and others about the keys, I'm trying to get more information about what could be the root cause

**Comment by ZachBacon** [comment] 2023-10-28 02:22
What version of the snap are you running, as I released 2.1.7 to the stable channel on snapcraft.io which should solve those issues

**Comment by yuripinto** [comment] 2023-10-31 04:21
You are right, @ZachBacon. I used `sudo snap install visualboyadvance-m --beta` and got the 2.1.4 version with this keyboard bug. I upgraded to 2.1.7 and it's running fine here. Tks

**Comment by ZachBacon** [comment] 2023-10-31 13:17
> You are right, @ZachBacon. I used `sudo snap install visualboyadvance-m --beta` and got the 2.1.4 version with this keyboard bug. I upgraded to 2.1.7 and it's running fine here. Tks

I mean I worked hard on that release and also got permission to autoconnect the joystick plug for controllers from the snap store. Just to ensure this updated version was working perfectly. There's still some things I'm trying to fix up. But for now, I'm happy with 2.1.7 it's release quality enough to be in the release channel.

**Comment by budindepunk** [comment] 2024-06-22 09:19
> You are right, @ZachBacon. I used `sudo snap install visualboyadvance-m --beta` and got the 2.1.4 version with this keyboard bug. I upgraded to 2.1.7 and it's running fine here. Tks

Hello! When I install using snap I also get 2.1.4. When I use sudo snap refresh visualboyadvance-m it tells me there's nothing to update. How do I get to 2.1.7?

**Comment by p1utoze** [comment] 2024-07-27 15:38
> > You are right, @ZachBacon. I used `sudo snap install visualboyadvance-m --beta` and got the 2.1.4 version with this keyboard bug. I upgraded to 2.1.7 and it's running fine here. Tks
> 
> Hello! When I install using snap I also get 2.1.4. When I use sudo snap refresh visualboyadvance-m it tells me there's nothing to update. How do I get to 2.1.7?

I guess you need to purge the current version (including core18) and install core22 first. As @ZachBacon mentioned, the `beta` channel is 2.1.4 itself. You need to install using `stable` channel. You can check using `snap info visualboyadvance-m` which looks like this for me as of today:
```
  latest/stable:    2.1.8           2023-12-15 (725) 88MB -
  latest/candidate: ^                                     
  latest/beta:      2.1.4           2019-12-18   (2) 70MB -
  latest/edge:      2.1.9-gcf5cb40c 2024-07-27 (881) 93MB -
```

**Comment by ZachBacon** [comment] 2024-07-27 15:42
I'll be looking to update the stable branch this weekend I hope. I just got into a new job and it kinda has me busy. But this job also had me learning and working on my own time as well so I haven't had a whole lot of time for a while.

But I'll try and get things updated snap wise and flatpak wise.

**Comment by mosesintech** [comment] 2024-11-25 22:02
Any update on this? I've just downloaded visualboyadvance-m via the terminal and the keyboard isn't working at all.

**Comment by Squall-Leonhart** [comment] 2024-11-25 22:47
follow previous instructions

**Comment by mosesintech** [comment] 2024-11-25 23:18
My fault. I somehow didn't see the instructions comment by p1utoze. `stable` worked exactly like expected.

Thank you.

**Comment by Steelskin** [comment] 2024-11-25 23:53
I am going to close this as I believe this is no longer an issue. Please drop a comment if is not fixed and you have previously commented on this bug.

**Closed by Steelskin** 2024-11-25 23:53 UTC
Labels: bug
