### ISSUE TITLE
Keyboard shortcuts don't work

### ISSUE THREAD

**Issue by BeyondTheHorizon** [visualboyadvance-m/visualboyadvance-m#88] opened 2017-02-25 09:55 UTC
I've tried using keyboard shortcuts with VBA-M, but for some reason they don't do jack. For example, when using CTRL+P while playing a game, this should pause the game, but it doesn't.

I'm using the latest release—6ecab80—with Windows. I can't find the interface (wx or SDL).

Thank you for your time.

**Comment by bryc** [comment] 2017-02-25 22:13
I am experiencing the same issue. In the latest two releases `931fda4` and `6ecab80`, I am unable to use `CTRL+R` for reset and save state shortcuts `SHIFT+F1/F1`. The older Beta-3 release `f7f67ff` is unaffected.

**Comment by rkitover** [comment] 2017-02-28 22:33
@BeyondTheHorizon @bryc 

I've been doing lots of work on the keyboard related code, I will try to look at this soon.

**Comment by rkitover** [comment] 2017-02-28 23:26
@BeyondTheHorizon @bryc 

I cannot reproduce this, in my msys2 built binary and the latest release shortcuts like CTRL+P and ALT+ENTER work fine.

Can you make sure that you don't have any part of the shortcut mapped to a game key, e.g. if you mapped CTRL or P then CTRL+P will **NOT** work.

Also can you please provide some details about your environment, whether you are using any special keyboard software like AutoHotKey etc.

**Comment by bryc** [comment] 2017-03-01 00:32
Well damn, I also cannot seem to reproduce it anymore. 

A little background info:

When I first tested the latest builds, everything seemed to work - i distinctly remember using keyboard shortcuts for reset and pause.

Then I tried using save states in Mega Man V. It seemed to save fine, but upon loading, it corrupted the game. I thought maybe I was using an incompatible save state between versions. Or maybe it was an issue with i686 or x86-64 specifically. I couldn't determine exactly what was going on, but I knew that freshly created save states were failing to load on certain builds.

Then, out of nowhere, keyboard shortcuts just stopped working. I found this bug and immediately related to it. And noticed that beta-3 worked fine. 

In fact, I can reproduce that fact: MMV save states work in beta-3 but not the newest two builds, it loads.

I think it affects all SGB games.. they load slowly and save states are corrupt when loaded.

However I cannot reproduce the keyboard issue anymore. 

I did notice this, at the same time the bug occured:

![image](https://cloud.githubusercontent.com/assets/1408749/23440812/820e28a6-fdec-11e6-9af2-b3fc0e4a25f1.png)

The key shortcut dialog has incorrect text labels. No clue if its related, but "Reset All" neither fixed it when it was broken (I tried that to see if it'd fix it), or causing it now.

**Comment by rkitover** [comment] 2017-03-01 01:35
@bryc thanks for the detailed info, I don't know what is going on here myself, it seems the shortcuts are not written to the `.ini` at all but somewhere else.

**Comment by bryc** [comment] 2017-03-01 02:13
@rkitover can you reproduce it? 

I have more information:

CTRL+Q (Exit) and CTRL+O (Open) works when first starting the program, but once a game starts, it cannot be used anymore. It appears that all keyboard shortcuts get disabled. If the ROM is closed, the keyboard shortcuts seem to be usable again.

I also noticed that when I unplug my controller and restart the emulator, the issue is nonexistent, I can use shortcuts when a ROM is loaded.

In fact, when I unplug my controller, even when the emulator is currently running a game, it immediately lets me use keyboard shortcuts again. 

When I plug back my controller, keyboard shortcuts work, but VBA-M cannot detect my controller or take set inputs.

When I re-open emulator with controller plugged in, it again disables keyboard shortcuts like before.

**Comment by rkitover** [comment] 2017-03-01 03:45
@bryc yeah there may be some leftover cruft that writes to the registry, will need to investigate.

It looks like the accel dialog uses wxKeyTextCtrl while the game key dialog uses wxJoyKeyTextCtrl, this is in the xrc.

The widgets themselves are in src/wx/widgets

I don't think the code itself has any support for binding accels that are not game keys to joystick controls because the joystick controls are done with SDL and handled separately.

**Comment by BeyondTheHorizon** [comment] 2017-03-01 07:12
@rkitover Reading this has been very insightful. And @bryc, you are right about it working when the emulator hasn't loaded a game or has a controller in.

UPDATE: I think I've found the problem! It has something to do with the default input for the Special controls (as you probably already know, the Input Configure option brings up a window with two tabs, "Standard" and "Special", along with tabs to select each player). Once I cleared the Special controls except for "Speed Up" and "Screenshot", I could use keyboard shortcuts once I restarted VBA-M.

I hope this solution is universal and works for everybody.

**Comment by bryc** [comment] 2017-03-01 16:42
@BeyondTheHorizon I can reproduce it. It seems to work but reverts back if defaults are used again. 

I isolated "Joy1-Axis2-" as the culprit for me (default binding for Motion Down). It is the only binding that needs to be removed to fix the issue:

![image](https://cloud.githubusercontent.com/assets/1408749/23469122/bf02aad2-fe70-11e6-8224-adf1a7f908ad.png)

Did the keyboard shortcuts ever work i.e. when you first started using the newest builds were keyboard shortcuts broken to begin with, or only after tinkering with settings?

**Comment by BeyondTheHorizon** [comment] 2017-03-01 17:11
@bryc If it helps, the keyboard shortcuts were broken when I first started using the latest release.

**Comment by kelpso** [comment] 2017-05-01 01:47
I've figured out the exact culprit. It seems previous VBA-M versions were much less picky about controls. When a trigger is pressed past its halfway point, its value is registered under (for example) Joy1-Axis2+, whereas if it hasn't reached the halfway point yet, its value is registered as Joy1-Axis2-. This normally works fine, except this version of VBA-M has included not being pressed at all as being -, so when that state is registered to an action, the action will be consistently fired (unless the trigger is once again moved past its halfway point to untrigger the - action and instead trigger the + action).
I believe previous versions of VBA-M may not have even accepted - actions and so this is a bug resulting from the messing around with keyboard shortcuts.

**Comment by Ivandsi2211** [comment] 2018-03-29 21:29
I'm also having issues with the shortcut keys in the latest release, it might be because of what you said (@kelpso) but I'm not really sure. Also the fact that it randomly works and sometimes it doesn't, could point that maybe sometimes it's reading + or - on the trigger and sometimes something else.
As an extra thing, the shortcuts work perfectly before running any games so, basically, before the emulator needs to check for the input you use in a game.

**Comment by nicklemarr** [comment] 2018-05-12 01:55
Same issue.

**Comment by AquaSurge101** [comment] 2018-05-17 09:09
I solved the issue by clearing all the special keys except Speed up and screenshot. I hope this works for everyone :)

**Comment by Bjonnfesk** [comment] 2018-08-05 11:44
I appear to have experienced the exact same problem as @bryc describes: Keyboard shortcuts work fine when VBA-M is started _sans controller_, but with a controller connected, CTRL+O and CTRL+Q work (although I usually have CTRL+Q and CTRL+W unbound as I have been burned by accidentally pressing these combinations instead of **CTRL+S** after difficult Pokèmon fights) before loading a ROM, but once a ROM is loaded, all keyboard shortcuts are disabled. 

Unbinding Joy1-Axis2- fixed the issue.

Oddly enough, I cannot recall ever having experienced this while using an _original Sony_ PlayStation 4 controller. It only happened after I misplaced my genuine DualShock and started using a cheap aftermarket controller branded, rather surprisingly, "Arrogant Bastard". However, from the previous comments here, it appears this must have been coincidence; I included it anyway because with programming, you quite frankly never know what might turn out to be relevant.

**Comment by retro-wertz** [comment] 2018-08-19 01:49
as a workaround for  shortcuts not working when game is already running, the culprit here is due to the nature of some analog triggers (at least on my case with xbox360). removing remaps(was set default for Motion Up/Down) for any triggers should resolve most shortcut key issues.

**Comment by retro-wertz** [comment] 2018-12-09 09:42
https://github.com/visualboyadvance-m/visualboyadvance-m/issues/276#issuecomment-423805638

MORE INFORMATION:
Hotkeys also do not work,when you are pressing/holding a key on gamepad (which is what is similarly happening when the analog triggers are still assigned to joypad buttons)

**Comment by Bjonnfesk** [comment] 2018-12-13 20:02
> [#276 (comment)](https://github.com/visualboyadvance-m/visualboyadvance-m/issues/276#issuecomment-423805638)
> 
> MORE INFORMATION:
> Hotkeys also do not work,when you are pressing/holding a key on gamepad (which is what is similarly happening when the analog triggers are still assigned to joypad buttons)

Correct.

**Comment by rkitover** [comment] 2018-12-28 12:52
This is essentially fixed in master now, although there is a lot more work to do to fix things properly and make some improvements to the joystick code.

**Comment by rkitover** [comment] 2018-12-29 05:57
The last issue was joystick buttons blocking hotkeys and that's now fixed in master, looking at other joystick issues.

Me and @ZachBacon will try to get a release out soon.

**Comment by retro-wertz** [comment] 2019-01-15 05:35
this should be fixed in latest commit....

**Comment by Stargateur** [comment] 2019-04-04 02:03
turbo mode assign to `D` doesn't work, but `alt+D` works on 2.1.1 64bit windows precompiled build

**Comment by denisfa** [comment] 2019-07-18 15:59
@rkitover This was very like fixed at some moment in the past. I can't reproduce the joystick issue, and the keybinding was done not so long ago.

@Stargateur If you are still around, your keybinding issue was fixed and it will be available on next release!

**Comment by rkitover** [comment] 2019-07-18 19:44
The only remaining issue is that the keybind editor is too sensitive when picking up the analog axis, it binds e.g. axis+ and then immediately adds axis-.

**Comment by rkitover** [comment] 2019-07-19 12:47
Ok I added a better hack for 360 triggers in 2fcad3f8 and that problem is gone.

I think we can close this now.

**Closed** 2019-07-19 12:48 UTC
Labels: bug, fixed, input
