### ISSUE TITLE
[GB/GBC]: add Super Game Boy / Super Game Boy 2 colors/palettes

### ISSUE THREAD

**Issue by Squidward22** [visualboyadvance-m/visualboyadvance-m#957] opened 2022-05-24 21:30 UTC
### Request box

Super Game Boy / Super Game Boy 2 color/palettes are used from Super Game Boy / Super Game Boy 2 MENU (By pressing L+R button) from Super Game Boy / Super Game Boy 2 cartridge for SNES

See:
![0 SGB Menu 1](https://user-images.githubusercontent.com/105673473/170133771-bd5a22c1-95c8-4dde-8a85-e87d59418156.png)
![0 SGB Menu 2](https://user-images.githubusercontent.com/105673473/170133792-fd7baf74-6cbf-4187-a8ac-08890854d6ad.png)
![0 SGB Menu 3](https://user-images.githubusercontent.com/105673473/170133802-d12e9f8a-6b93-4166-b7c7-3b6af131a1f4.png)
![0 SGB Menu 4](https://user-images.githubusercontent.com/105673473/170133813-49068a63-7336-4bea-8210-40ea3957c2a4.png)
![0 SGB Menu 5](https://user-images.githubusercontent.com/105673473/170133823-7f080ec1-5762-4868-94fa-2f60a19d6571.png)

Super Game Boy / Super Game Boy 2 colors/palettes:

> SGB 1-A
![SGB 1-A](https://user-images.githubusercontent.com/105673473/170133966-3316ef70-11ca-407d-a834-4aad4a6a68a8.png)

> SGB 1-B
![SGB 1-B](https://user-images.githubusercontent.com/105673473/170133987-e0fc151b-1757-4493-8361-ecd3c85a2893.png)

> SGB 1-C
![SGB 1-C](https://user-images.githubusercontent.com/105673473/170134020-feba56fd-c49b-4aee-94d4-434dda345ba5.png)

> SGB 1-D
![SGB 1-D](https://user-images.githubusercontent.com/105673473/170134028-6bc59db8-0762-4ddf-bd6b-842e7ef92149.png)

> SGB 1-E
![SGB 1-E](https://user-images.githubusercontent.com/105673473/170134068-283a5ace-2e73-45c4-b7bd-ca4fec6bbd2f.png)

> SGB 1-F
![SGB 1-F](https://user-images.githubusercontent.com/105673473/170134162-c4ee1596-c1a1-46f9-8a1e-d6ac826a437b.png)

> SGB 1-G
![SGB 1-G](https://user-images.githubusercontent.com/105673473/170134185-b01b6152-2b65-48ae-a2aa-e8550b61dd05.png)

> SGB 1-H
![SGB 1-H](https://user-images.githubusercontent.com/105673473/170134299-8aea90f7-906f-47e6-b89c-0232ed9af9a1.png)

> SGB 2-A
![SGB 2-A](https://user-images.githubusercontent.com/105673473/170134325-5725f437-7519-49d2-8d80-9a4140847e57.png)

> SGB 2-B
![SGB 2-B](https://user-images.githubusercontent.com/105673473/170134349-158af026-49b2-4f2e-87e6-051d01521b7e.png)

> SGB 2-C
![SGB 2-C](https://user-images.githubusercontent.com/105673473/170134373-bed6c191-621e-4edd-9605-3b1beb7b05e7.png)

> SGB 2-D
![SGB 2-D](https://user-images.githubusercontent.com/105673473/170134407-f7c6112e-b120-4089-a6a2-4dd34b50b11a.png)

> SGB 2-E
![SGB 2-E](https://user-images.githubusercontent.com/105673473/170134435-f3cda675-0c7a-471e-9cbd-28eb6d052219.png)

> SGB 2-F
![SGB 2-F](https://user-images.githubusercontent.com/105673473/170134455-edd4c077-bbaa-4ae8-9b43-2f01a59adba1.png)

> SGB 2-G
![SGB 2-G](https://user-images.githubusercontent.com/105673473/170134494-04cbab7d-647d-4ab0-a0b6-0a23e243629f.png)

> SGB 2-H
![SGB 2-H](https://user-images.githubusercontent.com/105673473/170134516-ea2f9484-b7ad-4c04-b86a-4a535ba66909.png)

> SGB 3-A
![SGB 3-A](https://user-images.githubusercontent.com/105673473/170134554-fdd1edbe-7294-438b-ae5c-98cd36500a8b.png)

> SGB 3-B
![SGB 3-B](https://user-images.githubusercontent.com/105673473/170134571-20f44abf-8fd4-473a-a438-733b8bac07e4.png)

> SGB 3-C
![SGB 3-C](https://user-images.githubusercontent.com/105673473/170134612-ea0d5c25-5bf5-46bb-b343-8f78de817c43.png)

> SGB 3-D
![SGB 3-D](https://user-images.githubusercontent.com/105673473/170134630-55d2ed4a-43f8-4395-b901-c88e3cee2b8d.png)

> SGB 3-E
![SGB 3-E](https://user-images.githubusercontent.com/105673473/170134660-caaf6c0e-e4bd-4702-853c-8d4c0120f6d7.png)

> SGB 3-F
![SGB 3-F](https://user-images.githubusercontent.com/105673473/170134692-5016fc0e-c0c4-4e3a-a3b9-2583411e1b39.png)

> SGB 3-G
![SGB 3-G](https://user-images.githubusercontent.com/105673473/170134705-88d49e8b-f5b7-49d7-b3e2-78587359685d.png)

> SGB 3-H
![SGB 3-H](https://user-images.githubusercontent.com/105673473/170134720-14ab3b12-7be1-4aff-87b7-37156d82b7a1.png)

> SGB 4-A
![SGB 4-A](https://user-images.githubusercontent.com/105673473/170134749-b22a2db3-3597-4f98-b226-4b88d01d3361.png)

> SGB 4-B
![SGB 4-B](https://user-images.githubusercontent.com/105673473/170134760-ebfc9b9f-d23a-4c0e-bfe1-03b525e3b5d5.png)

> SGB 4-C
![SGB 4-C](https://user-images.githubusercontent.com/105673473/170134794-2418b853-5b7f-4604-ac46-f106d9d5a275.png)

> SGB 4-D
![SGB 4-D](https://user-images.githubusercontent.com/105673473/170134804-9867cee3-a351-49b6-bb2f-ab6b2e77c332.png)

> SGB 4-E
![SGB 4-E](https://user-images.githubusercontent.com/105673473/170134813-f581de17-4c72-4b47-ac58-1df40706cc28.png)

> SGB 4-F
![SGB 4-F](https://user-images.githubusercontent.com/105673473/170134823-805ac5ce-6250-4494-bc40-5da90f504696.png)

> SGB 4-G
![SGB 4-G](https://user-images.githubusercontent.com/105673473/170134833-e0810901-0b0a-4880-a325-5e004cd8e5c0.png)

> SGB 4-H
![SGB 4-H](https://user-images.githubusercontent.com/105673473/170134845-bb2f1ba8-5d69-4502-936a-2d607b34eb74.png)

### Reason box

on GB Palette feature

### Examples

Super Game Boy / Super Game Boy 2 color palettes are used from Super Game Boy / Super Game Boy 2 for SNES

**Comment by Squall-Leonhart** [comment] 2022-05-24 21:54
Duplicate of #933

**Closed by Squall-Leonhart** 2022-05-24 21:54 UTC
Labels: enhancement

**Comment by CraftFan23** [comment] 2022-05-25 05:02
#957
#950
#941 

Are duplicates of #933

@Squidward22 Stop spamming the same requests about Super Game Boy / Super Game Boy 2 color palettes from SGB / SGB2 Game for SNES. VBA-M & Gambatte is inaccuracy (MBC6, MBC7, Pocket Camera, Unlicensed some mappers are unsupported). mGBA is excellent & accuracy than VisualBoyAdvance-M (VBA-M), Gambatte. Such as: Game Boy DMG palette from GB hardware, Game Boy Color palettes from GBC hardware, Super Game Boy / Super Game Boy 2 palettes from SGB / SGB2 Game for SNES, GB Pocket palette, GB Light palette from GB Pocket hardware, supported mappers: MBC1, MBC2, MBC3, MBC4, MBC5, MBC6, MBC7 (Kirby - Tilt 'n' Tumble), Pocket Camera (Game Boy Camera), Unlicensed mappers, it's Like My OldBoy!, My Boy!, Pizza Boy GBC, Pizza Boy GBA, Real GB, SGB, SGB2, pocket, GBC, GBA Hardware, Link Cable support, Trade support from Pokémon Trading Game, SGB Borders, Game Boy Printer support.

Just stop spamming.

**Comment by Squall-Leonhart** [comment] 2022-05-25 05:22
its sad that you created a 5th account to bump this issue created by your 4th account.

**Comment by Squidward22** [comment] 2022-06-04 10:59
It may will be added Super Game Boy / SGB2 color palettes from SNES or not. I may will see on RetroArch next update.
