### ISSUE TITLE
Doesn't remember GBA BIOS path

### ISSUE THREAD

**Issue by Nicholas-Steel** [visualboyadvance-m/visualboyadvance-m#191] opened 2018-02-09 17:29 UTC
### Expected behavior
Emulator should load games without errors/warnings.

### Actual behavior
Emulator displays a message that it has failed to load the GBA BIOS.

---------------------------
VisualBoyAdvance-M Error
---------------------------
Could not load BIOS 
---------------------------
OK   
---------------------------

### Steps to reproduce the behavior
Set path to GBA BIOS in the emulator configuration settings.
Quit Emulator.
Open Emulator.
Observe the path to the GBA BIOS is now blank.
Launch GBA game.
Error occurs but game runs without issues (could be problematic for Save State compatibility though).

### ROM details
All GBA games.

### Build details
Windows 10 Pro x64 v16299.214

v2.01 emulator.

**Comment by ZachBacon** [comment] 2018-02-09 17:33
Duplicate of an issue we already have opened. Closing

**Comment by ZachBacon** [comment] 2018-02-09 17:34
Also I've confirmed recently that it does remember in the ini, but the issue is that it's not making use of it, saying it's invalid. So I'll have to see about getting that sorted.

**Closed by ZachBacon** 2018-02-09 17:33 UTC

**Comment by Nicholas-Steel** [comment] 2018-02-09 17:42
I did check the first 2 pages before reporting, either I didn't check the pages well enough or I should've checked more pages. Also, where would I go to suggest a feature request?

**Comment by ZachBacon** [comment] 2018-02-09 17:47
At the moment we aren't going to entertain feature requests just yet, mainly due to the fact we are trying to fix existing bugs that happened in the UI change over. Once we are secure and feel the bugs are sufficiently fixed then we'll entertain the possibility of adding features.

**Comment by ZachBacon** [comment] 2018-02-09 17:52
Or, if you have coding experience and want to expedite a feature to be added, I'd say feel free to contribute. We sorely could use the extra help since it's just two people working on vba-m now

**Comment by Nicholas-Steel** [comment] 2018-02-09 17:54
I don't have such experience unfortunately :/

**Comment by ZachBacon** [comment] 2018-02-09 17:54
Fair enough. I do thank you though without people reporting issues etc, I wouldn't of continued supporting vba-m as I've done.
