### ISSUE TITLE
GBA Bios Path does not get saved.

### ISSUE THREAD

**Issue by cooperate** [visualboyadvance-m/visualboyadvance-m#162] opened 2017-10-29 09:57 UTC
### Expected behavior
VBA-M to remember BIOS path for GBA
### Actual behavior
VBA-M does not remember file path (at least as far as the GUI is showing me, despite my .ini and .cfg files having correct path ).  if the file path does not have anything in it in the GUI, when I launch bios it gives error "Could not load bios".  

Upon selecting the bios in the GUI it loads fine.  However upon exiting and opening the emulator again it loses these settings.

### Steps to reproduce the behavior
Launch vba-m.
Attempt to load gba BIOS.
Receive error message.
Enter correct bios path in Options->Game Boy Advance->Configure->Boot ROM->Browse for correct path.
Load gba BIOS again.
Boots correctly.
Exit Emulator.
Verify .cfg/.ini
Start Emulator
Load gba BIOS.
Receive error again
Check bios in Options->Game Boy Advance->Configure->Boot ROM.
Path is empty.

**Comment by ZachBacon** [comment] 2017-10-29 09:58
duplicate of #153

**Closed by ZachBacon** 2017-10-29 09:58 UTC
Labels: bug, duplicate
