### ISSUE TITLE
[Bug]: opengl problems on Wayland

### ISSUE THREAD

**Issue by neofeo** [visualboyadvance-m/visualboyadvance-m#1028] opened 2022-10-19 02:24 UTC
### Expected behavior?

opengl was detected on configuration but still doesn't appear on video output!

```
display: :1  screen: 0
direct rendering: Yes
Extended renderer info (GLX_MESA_query_renderer):
    Vendor: Panfrost (0xffffffff)
    Device: Mali-G52 (Panfrost) (0xffffffff)
    Version: 22.3.0
    Accelerated: yes
    Video memory: 3663MB
    Unified memory: yes
    Preferred profile: core (0x1)
    Max core profile version: 3.3
    Max compat profile version: 3.3
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.1
OpenGL vendor string: Panfrost
OpenGL renderer string: Mali-G52 (Panfrost)
OpenGL core profile version string: 3.3 (Core Profile) Mesa 22.3.0-devel (git-26d1b0ca02)
OpenGL core profile shading language version string: 3.30
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
```

configuration details with cmake
[CMakeCache.txt](https://github.com/visualboyadvance-m/visualboyadvance-m/files/9816321/CMakeCache.txt)

### Actual behavior?

installed precompiled version on manjaro and didnt work. I compiled it just to enable SDL2 since it seems it wasnt enabled on manjaro repo version but still doesnt work. opengl was properly detected when running cmake!

### Steps to reproduce the problem

1.
2.
3.
4.
5.
...

### Error messages?

If this is a crash bug, and you have the time and inclination, please provide a symbolic backtrace.
Instructions for doing so are [here](https://github.com/visualboyadvance-m/visualboyadvance-m/blob/master/README.md#reporting-crash-bugs).

### What game were you playing

<Some of this information can be provided with a screenshot of Rom Information, SAVE TYPE for GBA titles can be obtained from Options > Game Boy Advance > Config>
Title:
GB, GBC or GBA:
ROM CODE: 
BIOS Used?: (Share crc hash)
SAVE TYPE: (Attach Battery or Savestate here)
Clean, Intro'd or Hacked?:(Attach Patch here)

### What settings are you using?

Video driver (simple, opengl):
Sound driver (directsound, xaudio, openal, SDL):
Scale Filter Used?:

### Specifications and Build details

compiling master on aarch64 odrid N2 with manjaro kernel 5.19

### Copyright Compliance

- [X] There are no infringing files attached to this bug report.

**Comment by Steelskin** [comment] 2022-10-19 02:33
Are you running Wayland? OpenGL is disabled on Wayland right now.

**Comment by neofeo** [comment] 2022-10-19 02:37
Ohh.. yes, that's  the problem.. and the emulator seems working way better on x11.. that's  a pitty. May be a priority (wayland support) thabks!!!!!

**Comment by neofeo** [comment] 2022-10-19 02:43
@Steelskin there is any wayland feature request?? The emulator runs stupidly great on X11, not near as good as on wayland with simple output sadly

**Comment by ZachBacon** [comment] 2022-10-19 02:45
It's an eventuality that will happen, right now the opengl code is primarily tied with the implementation wxwidgets has.

**Comment by rkitover** [comment] 2022-10-21 17:31
@neofeo Please try master with wx 3.2 or greater.

**Comment by rkitover** [comment] 2022-10-21 19:21
VSync support on Wayland now in master as well.

**Comment by neofeo** [comment] 2022-10-22 00:21
okay @rkitover ! yes, opengl works, vsync seems to work too. but there is some strange issue.. maybe it's not strictly related to the emualtor but related to wx.
![Screenshot_20221021_211925](https://user-images.githubusercontent.com/84641119/197307791-0158de2b-f380-4331-b7a1-9b33a7363d58.png)

**Comment by rkitover** [comment] 2022-10-22 01:55
Is this with 3.2.0 or 3.2.1? If the former, can you try wx master and/or 3.2.1? I can give you a small script for installing wx to `/usr/local`.

**Comment by neofeo** [comment] 2022-10-22 02:01
Maybe we need more feedback by others. Reopening?

**Comment by rkitover** [comment] 2022-10-22 03:11
It does work for me in KDE wayland. What happens when you resize or stretch the window? Are you using any kind of scaling?

**Comment by neofeo** [comment] 2022-10-22 03:13
Well, somehow it doesnt work great at all resizing the window, or selecting 1x to 5x etc.. ot does nothing at all..

**Comment by neofeo** [comment] 2022-10-22 03:15
Let's  leave it open for new testers on wayland (yes, I use kde plasma)

**Comment by rkitover** [comment] 2022-10-22 10:54
Do you see this on xorg too or only in Wayland?

**Comment by rkitover** [comment] 2022-10-22 11:11
On second look it seems like the image is just not being centered, this is supposed to happen when "keep aspect ratio" is enabled, and it is by default, except the image is supposed to be centered there.

Is any of the image being cut off?

**Comment by rkitover** [comment] 2022-10-22 11:13
Also, you don't have to redo your git clone. You can just run:

```bash
git pull --rebase
rm -rf build
mkdir build
cd build
cmake .. -DCMAKE_BUILD_TYPE=Debug -G Ninja
ninja
./visualboyadvance-m
```

**Comment by rkitover** [comment] 2022-10-22 12:20
@neofeo Can you try again please, I think I fixed some glitches with the layout of the EGL panel.

**Comment by rkitover** [comment] 2022-10-22 21:27
@neofeo Never mind, that does not fix it. I managed to reproduce the problem, it seems like a recent wx commit fixed it, we may have to wait until 3.2.2, unless I find a workaround.

**Comment by rkitover** [comment] 2022-10-23 13:00
I have a temporary fix awaiting merge.

**Comment by neofeo** [comment] 2022-10-23 14:35
Thanks @rkitover . We should change the title for a more generic wayland issue! Nice work so far!!! I switched to x11 just bc of this emulator hahaha

**Comment by rkitover** [comment] 2022-10-24 10:34
@neofeo Please try master, incidentally @Steelskin was doing a related thing which makes all of this work much better.

I still need to clean this all up more and add more cmake support, but it should be more or less functional now.

**Comment by neofeo** [comment] 2022-10-24 11:23
Okay, I will soon !  Thanks!

**Comment by Mystro256** [comment] 2022-12-19 16:08
I was trying your build 2.1.5 on Fedora, and it look like the `#define private public` hack doesn't work.

Wouldn't it make more sense to try to extend the wxGLCanvas class to include something like this?
```
class wxGLCanvas_Custom : public wxGLCanvas
{
...
    wl_subsurface *GetSubsurface() const { return m_wlSubsurface; }
};
```

Then in MoveWaylandSubsurface, use `win->GetSubsurface()`?

I would need to dig into the code to understand if this is possible, but in theory if you're allocating the wxGLCanvas object, you should be able to create the object using the custom wxGLCanvas child class instead, then cast it to wxGLCanvas as needed.

**Comment by rkitover** [comment] 2022-12-19 17:12
What is the error though? Is the wx on Fedora 3.2.1?

I didn't put too much effort into this because it's only necessary until the next wx point release, we should find out when that's planned too.

**Comment by rkitover** [comment] 2022-12-19 17:15
Extending won't work because `m_wlSubsurface` is private, not protected.

Also note that if you just disable this patch, everything will still work, the canvas just won't be centered in the window, moving and resizing the window will still work fine.

**Comment by rkitover** [comment] 2022-12-21 02:55
@Mystro256 I got my wayland working again on my machine, so I'll take a look at this. My C++ buds told me of another method to get at private members using template instantiation, so I'll take a look and see if I can rewrite this a bit.

**Comment by Mystro256** [comment] 2022-12-22 16:15
Ok I'll workaround by removing the WAYLAND_MOVE_SUBSURFACE_BACKPORT definition, thanks!
Regarding the error, the compiler just ignores the "#define private public" line altogether it seems, so it never sets m_wlSubsurface to public and in turn errors when referenced.

________________________________

**Comment by rkitover** [comment] 2022-12-23 19:32
@Mystro256 I've reproduced the build fail in a fedora podman container, going to work on a fix.

**Comment by rkitover** [comment] 2022-12-27 02:54
@Mystro256 I suspect the issue here is precompiled headers for wx used on fedora, I'm trying to dig into this right now.

I tried replacing my code with the template instantiation hack, but those parts are just not in the headers, so I'm going to dig deeper into this.

**Comment by rkitover** [comment] 2022-12-28 13:10
So I've tracked this down to the wrong headers being conditionally read. The header `wx/unix/glegl.h` is not being read for some reason, I'll try to come up with a workaround. Maybe the fedora wx doesn't have wayland enabled, I'll check.

**Comment by rkitover** [comment] 2022-12-28 17:10
@Mystro256 so it looks like the fedora wx is compiled without egl surface support, if you open up:

`/usr/lib64/wx/include/gtk3-unicode-3.2/wx/setup.h`

you'll see that it has `wxUSE_GLCANVAS_EGL` set to `0`.

**Comment by rkitover** [comment] 2022-12-28 17:36
Furthermore, the resulting Fedora binary just throws an endless stream of runtime errors about nonexistent EGL support. So I have some work to do to remove Wayland support entirely in this configuration.

**Comment by rkitover** [comment] 2022-12-28 18:48
@Mystro256 so with the two linked patches, everything will compile and work on Fedora fine, but without OpenGL support under Wayland.

If you can reach out to the wx maintainers and ask them to enable EGL support, then OpenGL support under Wayland will be available, but the package will need to be recompiled.

By the way, I am using a less horrible hack to get the private member now, although that turned out to not be relevant.

**Comment by rkitover** [comment] 2022-12-28 18:48
Reopening to wait on Fedora wx being rebuilt with EGL support.

**Comment by Mystro256** [comment] 2023-01-23 19:44
Thanks! Yes I see it's much better now. I'll reach out to the fedora maintainer of WX when I have some time and get back to you.

**Comment by rkitover** [comment] 2023-01-31 06:12
I need to do one last thing here, I need to check the wx version dynamically and disable the patch if e.g. it was compiled for `3.2.1` but is running on `3.2.2`.

**Comment by rkitover** [comment] 2023-02-01 05:03
I added this check.

**Comment by rkitover** [comment] 2023-09-05 22:43
@Mystro256 this explains why fedora disables the EGL glcanvas and what the solution will be in the future:

https://github.com/wxWidgets/wxWidgets/issues/23833

**Comment by rkitover** [comment] 2023-09-06 00:22
Closing this because this is beyond our control now, I will try to contribute to the feature implementation in wxWidgets if I can.

**Comment by rkitover** [comment] 2023-09-10 23:19
I learned of a way to automatically launch under xwayland, I will implement this when EGL is not available.

**Closed** 2023-09-11 04:14 UTC
Labels: bug

**Comment by rkitover** [comment] 2023-09-11 04:38
@Mystro256 This is now completely fixed to the best of our ability, I will do a release so it gets into distros.

**Comment by rkitover** [comment] 2023-09-11 06:49
v2.1.7 is released with this commit.
