### ISSUE TITLE
Freezes when opening the second game with SDL audio

### ISSUE THREAD

**Issue by sergiobenrocha2** [visualboyadvance-m/visualboyadvance-m#84] opened 2017-02-22 02:51 UTC
### Actual behavior

Freezing when opening the second ROM. Crashes when opening the second GBA ROM.

### Steps to reproduce the behavior

Choose SDL in audio settings.

Open a GB/GBC game, then try open another, it'll freeze. Open a GBA game, then open another GBA game, it'll crash and you'll get this:

```
Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffb3fff700 (LWP 17198)]
0x0000000001558330 in ?? ()
(gdb) bt full
#0  0x0000000001558330 in ?? ()
No symbol table info available.
#1  0x00007ffff772a5fb in SDL_RunAudio (devicep=devicep@entry=0x1556a10) at /build/buildd/libsdl2-2.0.2+dfsg1/src/audio/SDL_audio.c:483
        silence = 0
        device = 0x1556a10
        stream = 0x17cd710 ""
        stream_len = 2048
        udata = 0x17d02b0
        fill = 0x4f2670 <SoundSDL::soundCallback(void*, unsigned char*, int)>
        delay = 11
#2  0x00007ffff778673d in SDL_RunThread (data=0x1558340) at /build/buildd/libsdl2-2.0.2+dfsg1/src/thread/SDL_thread.c:282
        args = 0x1558340
        userfunc = 0x7ffff772a4a0 <SDL_RunAudio>
        userdata = 0x1556a10
        thread = 0x1558000
        statusloc = 0x1558010
#3  0x00007ffff77d1279 in RunThread (data=<optimized out>) at /build/buildd/libsdl2-2.0.2+dfsg1/src/thread/pthread/SDL_systhread.c:72
No locals.
#4  0x00007ffff74fa184 in start_thread (arg=0x7fffb3fff700) at pthread_create.c:312
        __res = <optimized out>
        pd = 0x7fffb3fff700
        now = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140736213284608, -1725036879148407560, 1, 25772416, 140736213285312, 140736213284608, 1724904937141904632, 
                1725052957179979000}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
        pagesize_m1 = <optimized out>
        sp = <optimized out>
        freesize = <optimized out>
        __PRETTY_FUNCTION__ = "start_thread"
#5  0x00007ffff7b0f37d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
No locals.
```

### Build details

Ubuntu 14.04, GCC 4.9.2, libSDL 2.0.2, mesa 10.1.3

Interface (wx, SDL, default is wx):

master branch, last commit

**Comment by sergiobenrocha2** [comment] 2017-02-22 02:54
It's working fine with OpenAL

**Comment by rkitover** [comment] 2017-02-28 22:26
related to #46

**Comment by Mystro256** [comment] 2017-03-05 06:12
I believe #92 fixes this issue

**Comment by Mystro256** [comment] 2017-03-05 06:31
Yeah I'm having trouble reproducing this issue after applying #92 , it seems that this pull request fixes the issue.

There still is a random freeze, but seems to be related to #46  and unrelated to SDL.

**Comment by rkitover** [comment] 2017-03-05 13:41
Verified that #92 (merged) fixes the issue, without which SDL sound was completely broken on Windows anyway.

**Comment by rkitover** [comment] 2017-03-15 02:33
Fixed in this release:

https://github.com/visualboyadvance-m/visualboyadvance-m/releases/tag/throttle

closing.

**Closed by rkitover** 2017-03-15 02:33 UTC
Labels: bug, fixed
