### ISSUE TITLE
PC COMPATIBILITY

### ISSUE THREAD

**Issue by STRIKER9001** [visualboyadvance-m/visualboyadvance-m#104] opened 2017-04-06 22:32 UTC
### ROM details 

Which games are affected by the issue (please state if GBA or GB game): n/a

Which games, if any, are NOT affected by the issue (please state if GBA or GB game): n/a

### Option details

Video driver (simple, opengl or cairo): n/a

Sound driver (directsound, xaudio, openal, SDL): n/a

### Build details

Operating System (Windows, Mac, Linux (state distribution), etc.): windows (xp or 95 not sure)

If using Linux, specify if using xorg or Wayland: n/a

Version of code (pre-built binary version, or commit ref, or just "master"):

### Hardware details:

If relevant, the joystick you are using and the drivers you are using for it:

**Comment by ZachBacon** [comment] 2017-04-06 22:34
Your report needs more details. Your operating system, if it's 32bit or 64bit etc. Without more we can't begin to provide the necessary help.

**Comment by Squall-Leonhart** [comment] 2017-04-07 06:49
just mark as 'not a bug report' and close

**Comment by ZachBacon** [comment] 2017-04-15 13:26
Since I have not heard anything back from this, I am closing this issue.

**Closed by ZachBacon** 2017-04-15 13:26 UTC
Labels: incomplete-information, no-reply-from-requestor
