### ISSUE TITLE
Choppy frame rate

### ISSUE THREAD

**Issue by metalmight** [visualboyadvance-m/visualboyadvance-m#86] opened 2017-02-23 20:54 UTC
### Expected behavior
Smooth frame rate
### Actual behavior
Choppy framerate
### Steps to reproduce the behavior
Play a rom
### Build details
2.0.0 beta 2
Operating System (Windows, Mac, Linux, etc.):
Windows 10
Interface (wx, SDL, default is wx):
wx
Version of code (pre-built binary version, or commit ref, or just "master"):
I don't know
Any other relevant build information:

If this is e.g. a joystick or video issue, then the relevant hardware information:
Intel Core i3 laptop.

**Comment by ZachBacon** [comment] 2017-02-23 20:58
When giving detail. Please tell us, what graphics driver in vba-m, simple, opengl? Any filters being used? Details like that makes all the difference in a report

**Comment by metalmight** [comment] 2017-02-23 21:03
Graphics Driver opengl.  Filter xBRZ 4x.

**Comment by ZachBacon** [comment] 2017-02-23 21:08
Xbrz4 is slightly broken arm use 6

**Comment by metalmight** [comment] 2017-02-23 21:15
I tried 6, framerate is still choppy.

**Comment by ZachBacon** [comment] 2017-02-23 21:33
Do me a favour. Try each filter. And then try no filter and then report if it's a 64bit build you're using or i686 build. Debug or Release.

**Comment by metalmight** [comment] 2017-02-23 23:32
Filters: I tried each filter and no filter; still choppy.
Build: I am using the default download on this page: https://sourceforge.net/projects/vbam/  It doesn't say if it is 64bit or i686.  It doesn't say if it is Debug or Release but I assume Release.

**Comment by ZachBacon** [comment] 2017-02-23 23:34
Don't use those builds, they are outdated now. We ship the binaries on github under the releases tab

**Comment by metalmight** [comment] 2017-02-23 23:41
I can't find a releases tab; please post a link.

**Comment by ZachBacon** [comment] 2017-02-23 23:43
https://github.com/visualboyadvance-m/visualboyadvance-m/releases newest at the top, you'll find the current release fixes your input issues.

**Comment by metalmight** [comment] 2017-02-23 23:45
Should I download i686 or x86_64?

**Comment by ZachBacon** [comment] 2017-02-23 23:46
Most modern PC's are 64bit.

**Comment by metalmight** [comment] 2017-02-24 00:16
Now there are even more problems.  Frame rate is still choppy but the load game interface is very slow too.  In addition the right side of the screen is cut off in full screen mode which takes away the minimap in Metroid Fusion and you can't see doors which are on the right side of the screen.  Haven't checked cheats yet.

**Comment by metalmight** [comment] 2017-02-24 00:24
Cheats don't work.

**Comment by rkitover** [comment] 2017-02-28 22:30
@metalmight have you tried both Simple and OpenGL in the video config?

**Comment by metalmight** [comment] 2017-02-28 22:32
Yes.

**Comment by WizLizard** [comment] 2017-03-01 22:48
I experience this as well. Like a frame pacing issue or micro stutter. Very unpleasant. In fact a few emulators I use exhibit the same thing. Like Pcsx2 (opengl only), epsxe, and ppsspp. Very similar issue. Libretro port is fine. 4790k gtx 980.

**Comment by rkitover** [comment] 2017-03-02 01:58
@WizLizard have you tried the interframe blending options in the video config? Does it help at all?

**Comment by WizLizard** [comment] 2017-03-02 01:59
No I'll give it a try though tonight.

**Comment by WizLizard** [comment] 2017-03-02 08:02
@rkitover Tested on my 3 custom rigs. Interframe blending made no difference. I had every kind of filtering off. The behavior of the micro stutter/frame pacing issue is literally the same I get with epsxe's opengl plugins and ppsspp. It will temporarily stop stuttering going in and out of full screen mode, but eventually returns. Very noticeable and imo unplayable. This issue is the reason i use mednafen over epsxe for ps1 emulation. Even though epsxe has recently become the most accurate ps1 emulator as of 2016. I see so many emulators with this issue and it goes ignored by the devs and seems to be directly related to windows and opengl. I would love to see this resolved because maybe some info could be shared with other emulator devs.  On a side note the right side of the screen is being cut off again in the latest release from the release tab. It saddens me to say this but unless this issue is resolved I'll have to stick with the libretro core which sucks because it's probably not as up to date. Good luck trying to solve this issue because it seems very difficult to track down. Some emulators just seem to be doing something write in opengl that others aren't.

**Comment by rkitover** [comment] 2017-03-02 10:19
@WizLizard thanks for testing! Can you tell me which games you were using? I mostly play games like Advance Wars which are a map game with very little animation so I didn't notice this.

**Comment by WizLizard** [comment] 2017-03-02 10:23
Pokemon games and side scrollers like mario, donkey kong, kirby, metroid,
etc. Easiest way to see it is to just boot up pokemon ruby or something and
walk left and right. I can see it in every game though with any major
vertical or horizontal panning.

**Comment by WizLizard** [comment] 2017-03-08 08:44
I would like to mention this if it wasn't clear. Game speed is always at 100% and audio is never effected. Frame skipping is always off.

**Comment by WizLizard** [comment] 2017-05-29 10:18
@rkitover May be related https://github.com/PCSX2/pcsx2/issues/1437#issuecomment-301492954

**Comment by mirh** [comment] 2017-07-02 14:26
PCSX2 forum base is pretty retard
If you:

* are on Windows
* have a nvidia card
* can try 378 or nearly *older* driver
* put "vertical sync" forcibly off in the settings

Can you try [these samples](http://forums.pcsx2.net/Thread-Microstutter-when-in-fullspeed?page=5#pid562977) to see if any of them presents tearing (press SPACE to start the animation)?
Thank you.

**Comment by WizLizard** [comment] 2017-10-13 07:19
I can confirm that with the latest release this emulator is still extremely choppy/stuttery in windows to the point i can't even use it that how unpleasant it is.

**Comment by rkitover** [comment] 2017-10-13 13:09
@WizLizard please try the "Simple" video renderer (Options -> Video) and let me know if it makes a difference. If this is opengl related that will simpler to diagnose.

**Comment by WizLizard** [comment] 2017-10-15 00:26
@rkitover Hmmmm yeah, still happens with simple renderer. Maybe not opengl specific.

**Comment by Charadon** [comment] 2018-07-02 23:30
Happens on Antergos (Linux) also. Using the Open-Source Mesa Drivers.

**Comment by retro-wertz** [comment] 2018-07-02 23:41
@Charadon please test using the latest version.

if you are compiling it yourself, if you are on wayland, compile using wxgtk3 library, if non-wayland compile with wxgtk2... the included installdeps script should take care of these libraries but in some cases where it doesnt, manual manipulation should be done.

i am using arch myself. 99%

**Comment by Charadon** [comment] 2018-07-03 00:00
Yeah, I tested it using 2.1.0, and it still stuttered. (Which just got put on the main repository) I'll compile it myself and tell you the results.

**Comment by rkitover** [comment] 2018-07-03 00:18
No that is wrong, wxgtk3 is always preferred regardless of whether it's wayland or xorg.

If you are getting stuttering, try deleting your `~/.vbam/vbam.conf` and use the default settings.

**Comment by Charadon** [comment] 2018-07-03 00:22
Deleted vbam.conf, still happening :(

**Comment by rkitover** [comment] 2018-07-03 00:57
Try both the opengl and simple video output drivers.

**Comment by Charadon** [comment] 2018-07-03 01:13
Didn't work unforunately, still getting micro-stutters on both simple and opengl

**Comment by retro-wertz** [comment] 2018-07-03 01:48
a fix has just been merged. try fetch the new commit and try again.

thanks

**Comment by Charadon** [comment] 2018-07-03 02:05
Worked perfectly, micro-stuttering is completely gone.

**Comment by retro-wertz** [comment] 2018-07-03 02:08
great. thanks for the confirmation.

**Comment by retro-wertz** [comment] 2018-07-03 02:09
@ZachBacon we can probably safely close this issue then?

**Closed** 2018-07-03 02:34 UTC
Labels: bug, enhancement

**Comment by edison3322** [comment] 2021-12-29 00:20
> No that is wrong, wxgtk3 is always preferred regardless of whether it's wayland or xorg.
> 
> If you are getting stuttering, try deleting your `~/.vbam/vbam.conf` and use the default settings.

thank you for this comment. Helped me out even 4 years later lmao
