### ISSUE TITLE
[Bug]: Key Shortcuts set on controller doesn't work after opening the Cheat List window

### ISSUE THREAD

**Issue by wind50321** [visualboyadvance-m/visualboyadvance-m#1348] opened 2024-09-28 13:25 UTC
### Expected behavior?

<img width="1001" alt="key" src="https://github.com/user-attachments/assets/6cb12351-44ab-459a-8eda-5a3ea1355a45">

In Key Shortcuts I set Pause (toggle) on key P and Button 10 (Xbox One controller). It works great and I can use the controller to pause the game.

### Actual behavior?

<img width="410" alt="cheat" src="https://github.com/user-attachments/assets/e53b8bcb-530a-49d3-9c60-c52a393cdc46">

But when I open the Cheat List window and close it (no cheats added yet), I cannot use controller to pause the game anymore (other buttons set in Joypad Configuration still works).

<img width="960" alt="connected" src="https://github.com/user-attachments/assets/bbf5f5e5-e298-4f4e-aea0-702833362d5b">

If I open the Key Shortcuts window and close it, the emulator displays Connected Xbox One controller on the screen and it back to normal.

### Steps to reproduce the problem

1. Set Key Shortcuts - Pause (toggle) on key P and Joypad Button 10
2. Launch emulator and load the game (Pokemon FireRed)
3. The controller can pause the game at this point
4. Open Cheat List window and close it
5. The controller cannot pause the game now

### Error messages?

No.

### What game were you playing

Title: Pokemon - Fire Red Version (USA, Europe)
GB, GBC or GBA: GBA
GAME CODE: BRPT
BIOS Used?: No
SAVE TYPE: Automatic
Clean, Intro'd or Hacked?: Clean

### What settings are you using?

Video driver: OpenGL
Sound driver: OpenAL
Scale Filter Used?: No

### Specifications and Build details

VBA-M: 2.1.9 64-bit
OS: macOS 14.6.1
CPU: Apple M3

### Copyright Compliance

- [X] There are no infringing files attached to this bug report.

**Comment by rkitover** [comment] 2024-09-28 13:41
There have been some changes affecting key shortcuts recently, can you please try the latest release, which is `2.1.11` or a nightly?

**Comment by wind50321** [comment] 2024-09-28 13:59
I try the 2.1.11 and nightly mac 64-bit version, both they have the same issue.

<img width="787" alt="key_new" src="https://github.com/user-attachments/assets/3effce61-360a-40f3-a219-b156769b1fde">

Another problem, their Key Shortcut window can't be moved and no place to assign the key.

**Comment by rkitover** [comment] 2024-09-28 14:10
Thank you, we will look into this ASAP.

**Comment by Steelskin** [comment] 2024-09-28 17:29
I have a fix for the broken shortcut configuration dialog. However, I cannot reproduce your other issue. I suspect this is because you have Joy1 Button 10 already set to an emulated control. This should be fixed in the newest version too, in that the emulator will no longer let you assign the same input to both an emulated control and a shortcut.

**Comment by Steelskin** [comment] 2024-09-28 17:38
Sorry, didn't mean to close the issue before I can confirm your issue is actually fixed.

**Comment by wind50321** [comment] 2024-09-28 17:39
I only set button 10 in Key Shortcuts, not in Joypad Configuration. It works normal before I open the Cheat List window.

**Comment by Steelskin** [comment] 2024-09-28 17:44
The default configuration sets "Button 10" to the "R" key. Could you double-check if this is set for you?
Otherwise, could you tell me how you close the Cheat List dialog? Do you use the "X" on the top-left corner? Or the "OK" button?

It would also be very helpful to have your `vbam.ini` file. It should be in `${HOME}/Library/Application Support/visualboyadvance-m`

**Comment by wind50321** [comment] 2024-09-28 18:04
I have adjusted the Joypad Configuration

<img width="579" alt="joypad" src="https://github.com/user-attachments/assets/5be8ec3c-b88e-4224-b9a7-54f84f421572">

I use OK button to close the Cheat List dislog. Using X button has the same issue.

This is the file
[vbam.zip](https://github.com/user-attachments/files/17175748/vbam.zip)

**Comment by Steelskin** [comment] 2024-09-28 18:07
Sorry I keep pestering you, but with this configuration, could you try v2.1.11 again and report back? No need to change any setting.

**Comment by wind50321** [comment] 2024-09-28 18:17
It has the same issue in v2.1.9.

It works normal at first.
When I open the Cheat List dialog, the button 10 key shortcuts doesn't work then.
But if I open the Key Shortcuts or Joypad Configuration dislog, it seems to re-connet the controller and back to normal.

**Comment by Steelskin** [comment] 2024-09-28 18:25
Thanks, I can finally reproduce but only by opening the cheat dialog with Cmd+C. It works fine from the menu itself. Looking into why this is happening.

**Comment by wind50321** [comment] 2024-09-28 18:27
Yes same here, only Cmd+C causes this problem.

**Comment by Steelskin** [comment] 2024-09-29 20:13
I have a fix in code review. Thank you very much for the bug report!

**Closed** 2024-09-29 20:59 UTC
Labels: bug

**Comment by rkitover** [comment] 2024-10-03 14:12
@wind50321 Sorry I had some issues with government ****s, but you can download a nightly now with a fix.
