### ISSUE TITLE
Simple anyX have a black line on top

### ISSUE THREAD

**Issue by Yave-Yu** [visualboyadvance-m/visualboyadvance-m#583] opened 2019-12-24 01:40 UTC
In 2.1.4, if you use Simple 2X, 3X, 4X... filter, you will see a black line on top, looks like it ate 1 line pixel, but won't happen in older version like 2.1.0, so why?
Tested on Windows 10.

**Comment by denisfa** [comment] 2019-12-24 01:42
@Yave-Yu Thanks for the report.

It is a duplicate of #561. It will be fixed on next release/nightly.

**Closed by denisfa** 2019-12-24 01:42 UTC
Labels: duplicate
