### ISSUE TITLE
No longer loads paths that contain Unicode characters

### ISSUE THREAD

**Issue by bamq** [visualboyadvance-m/visualboyadvance-m#424] opened 2019-04-30 23:03 UTC
### Expected behavior
The ROM is loaded correctly.
### Actual behavior
Starting with release v2.1.2, VBA-M claims it isn't a valid ROM file.
### Steps to reproduce the behavior
Attempt to load a file whose path contains certain characters, such as é.
![image](https://user-images.githubusercontent.com/6969348/56998320-7f6efc80-6b70-11e9-8921-83c1815f2dd3.png)
![image](https://user-images.githubusercontent.com/6969348/56998344-93b2f980-6b70-11e9-9e3e-f155239475e2.png)

V2.1.1 used to work correctly
![image](https://user-images.githubusercontent.com/6969348/56998362-a4636f80-6b70-11e9-8530-b2c92f9c1d4d.png)

### Crash bugs

If this is a crash bug, and you have the time and inclination, please provide a
symblic backtrace.

Instructions for doing so are
[here](https://github.com/visualboyadvance-m/visualboyadvance-m/blob/master/README.md#reporting-crash-bugs).

### ROM details

Which games are affected by the issue (please state if GBA or GB game):

Which games, if any, are NOT affected by the issue (please state if GBA or GB game):

Include screenshots of ROM Information (File > ROM Information):

If you are using a BIOS file, please say which one.

### Option details

Video driver (simple, opengl):

Sound driver (directsound, xaudio, openal, SDL):

### Build details

Operating System (Windows, Mac, Linux (state distribution), etc.):
Windows 10 x64
If using Linux, specify if using xorg or Wayland:

Version of code (pre-built binary version, or commit ref, or just "master"):
v2.1.2 +
### Hardware details:

If your joystick or gamepad isn't working in Linux, please try to troubleshoot
using the information on this page:
https://wiki.archlinux.org/index.php/Gamepad **BEFORE** filing an issue. We use
SDL for joystick support, any problems will generally be an issue with SDL and
**NOT** the emulator.

If relevant, the joystick you are using and the drivers you are using for it:

**Comment by rkitover** [comment] 2019-04-30 23:20
duplicate of #410, sorry will fix for next release

**Comment by bamq** [comment] 2019-04-30 23:24
My bad, didn't realize someone else had mentioned it.

**Closed** 2019-06-23 14:34 UTC
Labels: bug, duplicate, fixed, gb-core, gba-core, localization, regression
