### ISSUE TITLE
Pressing SHIFT prevents me from using any other keys

### ISSUE THREAD

**Issue by bebebeebebe** [visualboyadvance-m/visualboyadvance-m#213] opened 2018-03-29 16:31 UTC
### Expected behavior
I configured my shift key to be 'B' button so i can use it as the 'B' button.
### Actual behavior
Shift (B) prevents me from using other keys at the same time and when I'm already pressing another key and then press shift key, it makes the previously pressed key stuck until I let go of shift.
### Steps to reproduce the behavior.
Pressing shift and trying to press other keys on the keyboard.
### ROM details
Pokemon Fire Red 1.1
### Option details
OpenGL, DirectSound
### Build details
Windows 10

**Comment by trlkly** [comment] 2019-05-12 04:01
Same issue here on Windows 7. It also occurs for Alt and Ctrl. It seems that it detects Ctrl-W, for example, as a different key than Ctrl and W.

**Comment by Nickiosaurus** [comment] 2019-05-22 00:52
Same issue, compiled on Linux Mint.
Example: (Pokemon Emerald)
*I use WASD for direction, Shift for 'B' or sprint. *
I can't start a sprint (Shift+WASD) in any direction when I start with Shift, then press a WASD key a moment later.
If I start with a WASD key, then press Shift.  My character starts to sprint.  When I try to stop, the WASD key, from the first sprint direction, is sustained or held down despite a lack of input.

**Comment by denisfa** [comment] 2019-05-22 17:47
Hey @Nickiosaurus, would you mind compiling a branch with a possible solution? I have examined a similar bug report that I believe It is direct related to this one.

`git clone -b fix-213 https://github.com/visualboyadvance-m/visualboyadvance-m.git`

Compile and run like you did for your previous testing. If it does not work, could you upload your config file so we can have a more precise testing setup?

**Comment by denisfa** [comment] 2019-05-23 00:00
@trlkly, @bebebeebebe Could you check if our new nightly build fixes this for you? We believe this is related to another issue. [Download here](https://github.com/visualboyadvance-m/visualboyadvance-m/issues/354#issuecomment-494907933).

**Comment by trlkly** [comment] 2019-05-23 03:22
@denisfa I can confirm that this version appears to fix the issue for me. I was able to hold down both CTRL and SHIFT while pressing WASD as the D-pad, as well as with the numpad arrow keys as the D-pad. Thus I can use my shield easily in Link's Awakening DX. 

Is there any reason I might not want to just use this version until a more official release comes out?

**Comment by ZachBacon** [comment] 2019-05-23 03:28
@trlkly Feel free, and if you find any other issues, let us know. That's why the nightlies exist, help us find these issues and then make a stable and the process begins to repeat.

**Comment by trlkly** [comment] 2019-05-23 05:53
@ZachBacon I was more wondering if there were any outstanding known issues in the nightlies that weren't in the original. I know there are times where I will not run the Nightly version of Firefox because they've added a feature and haven't ironed out the kinks yet.

**Comment by denisfa** [comment] 2019-05-23 15:46
@trlkly Thanks for the feedback. This version is just our latest build with this fix. It is meant to be a faster way to get a fixed version to an user wanting to play games.

Anyways, I will close this since it looks like the issue was solved.

**Closed by denisfa** 2019-05-23 15:46 UTC
Labels: bug, input

**Comment by rkitover** [comment] 2019-05-23 18:27
@trlkly we are hardly as serious an organization as mozilla, so both the releases and the nightlies are going to be in various states of brokenness, so use whatever works for you 😃

**Comment by denisfa** [comment] 2019-05-23 23:10
I had to do an extra commit here, because of an issue with controllers. I did some testing with both keyboard and controller, and everything worked. Hopefully, it was the last for this.

**Comment by rkitover** [comment] 2019-05-26 02:28
I posted a new nightly with the followup commit.
