### ISSUE TITLE
Large Icon issue in Windows Volume Mixer

### ISSUE THREAD

**Issue by FiiZzioN** [visualboyadvance-m/visualboyadvance-m#149] opened 2017-09-13 05:52 UTC
### Expected behavior

Normal icon size in the volume mixer to allow individual volume control rather than having to use the "Global" slider.

### Actual behavior

A <b>very</b> large icon preventing you from seeing the slider to adjust the volume. I have to use the "Global" slider, which is slightly annoying.

### Steps to reproduce the behavior

Open the ".exe" and load a ROM. Tried running the ".exe" as administrator and I've also tried using ".gb", ".gbc", and ".gba" files; it occurred with every one of them.

### Crash bugs

None

### ROM details

Pokemon Red (.gb), Yellow (.gbc), and Emerald (.gba)

### Option details

Picture of the very large icon: [Link Here](https://imgur.com/gMyrsYd)
I've also never had this happen with anything else I've used for last 10+ years. I'm just stating this so you know that this isn't a regular occurrence.

I'm also using the latest version on the release tab, commit ID: 2e8bee117d33d63745c5dd095254986e1985fde4

### Build details

Windows 10

System information: [Link Here](https://imgur.com/MN1alaj)

### Hardware details:

Using a controller but I highly doubt that would be the main culprit.

**Comment by ZachBacon** [comment] 2017-09-13 10:42
This is a duplicate of #121

**Comment by rkitover** [comment] 2017-09-19 23:42
Fixed in master in 3d792457.

**Comment by rkitover** [comment] 2017-10-14 18:53
Latest release `2.0.1` contains this fix.

**Closed by rkitover** 2017-10-14 18:53 UTC
Labels: bug, duplicate, fixed
