### ISSUE TITLE
Wx frontend freezes (almost) everything once a menu is open

### ISSUE THREAD

**Issue by ShadowStkr** [visualboyadvance-m/visualboyadvance-m#139] opened 2017-08-12 15:40 UTC
### Expected behavior

Once opening any of the menu options in the UI with a ROM loaded, the emulator should open said menu, let you choose whatever option you want, then return to the emulation once you're done.

### Actual behavior

Once opening a menu with a ROM loaded, the emulator freezes, apparently together with the desktop environment. I can't do anything except move my mouse and use Ctrl+Alt+(F key) to open virtual terminals. If I open said terminal, and terminate the emulator process through "killall -9 visualboyadvance-m", then return to the desktop environment, everything comes back to normal, but obviously, the emulator is not running anymore because I killed its process. If I return to the desktop environment without doing anything, everything remains frozen.

There are times when opening then closing a single menu one time doesn't make anything out of normal happen, but clicking on a certain option repeatedly, alternating through menus without closing one first by moving the mouse over another, or even closing and then clicking again causes the described problem.

If you open the menus without any ROM loaded, everything works normally.

### Steps to reproduce the behavior

Install vbam-wx on Arch through official repositories (commit 1eb768578bc0c4fa17396f573a4b37a652f12acd) by running "pacman -S vbam-gx", or simply compile it manually (I've tried commit 6ecab805e00e99c37bd23c425835ca35507cb593, which is marked as "latest release" on the Releases page). Open visualboyadvance-m, load any ROM and try opening a menu such as Options. If it doesn't freeze, try clicking fastly over any menu or alternating through menus by moving the mouse over another with one of them open. All games are affected by this issue since it's not a issue with the emulation itself, but I've personally tested it with two (Golden Sun and Harvest Moon: Friends of Mineral Town).

Operating System: Arch Linux, using xorg. The problem seems to happen on any DE (I've tested it on GNOME 3, Plasma 5, XFCE and MATE).

### Hardware details:
AMD FX-6300
Radeon R9 270 (using open-source drivers)

**Comment by rkitover** [comment] 2017-08-12 19:31
When a game is loaded, menu events cause emulation to pause, including the sound driver.

The default sound driver on Linux is OpenAL.

Can you please try switching to a different sound driver, such as SDL, and seeing if the issue persists?

Also, can you try pausing manually with `Ctrl + P` (Pause from the Emulation menu) with both sound drivers, and seeing if that also causes the lockup.

I will see if I can reproduce this issue on my various Linux VMs, but can't guarantee anything because these types of issues are often not reproducable.

Thank you!

**Comment by ZachBacon** [comment] 2017-08-12 19:37
Also, could you try compiling git master, the binary that archlinux has compiled is outdated and hasn't been updated in a bit.

**Comment by ShadowStkr** [comment] 2017-08-12 23:07
I tried rkitover's suggetion, however, in a reverse manner. When I opened the audio settings, the audio was set to SDL. Setting to OpenAL stopped the lockup from happening. I tried changing back to SDL after that and the lockup happened again. 

I tried ZachBacon's suggestion as well. Although Arch's official repository is outdated, compiling git master and running the compiled visualboyadvance-m still produces the same problem, although it seems to happen less frequently (the version in Arch's repositories almost always locks up just from trying to open any menu one time, while the git master one tends to lock up after I navigate a bit through them in the manners I described before - alternating menus without closing them, repeatedly opening and closing).

Anyway, I hope this gives a good idea of where the problem lies. I'll be using OpenAL for now.

**Comment by rkitover** [comment] 2017-08-12 23:15
@ShadowStkr awesome, thanks very much for testing, so now we know that the problem is in `soundPause()` in the SDL driver and I'll see if I can fix it.

**Comment by rkitover** [comment] 2017-08-15 22:38
@ShadowStkr I committed a temporary workaround that fixes the threads deadlock at least, but on resume from pause (e.g. closing a modal dialog) there is no sound for 2-3 seconds, so it still needs a proper fix.

**Comment by ShadowStkr** [comment] 2017-08-16 19:20
Thanks. The lockup doesn't happen anymore, but SDL sound is very garbled to me for some reason. Furthermore, when I pause, instead of the emulator stopping any sound and taking 2-3 seconds for it to come back once unpaused like you described, it emits a horrible noise, like the sound had freezed, until I unpause it (when the audio comes back instantly).

I'm also having another problem with both sound plugins relating to channel volume (when I load a save state, the volume on certain channels become too low, almost inaudible, which is only fixed by reloading/reseting the ROM or reopening the emulator). I'm having another problem related to input but I'll open another issue for that one.

**Comment by rkitover** [comment] 2017-08-16 21:44
@ShadowStkr I'm pretty sure I know the source of the "horrible noise" issue you describe, I need to fix the SDL audio callback to write silence to the buffer when nothing is playing. I'll try to fix this shortly.

For the channel volume issue, can you please open a separate issue?

**Comment by ShadowStkr** [comment] 2017-08-16 22:05
Of course. I'll open one.

**Comment by rkitover** [comment] 2017-08-16 22:25
@ShadowStkr hopefully fixed the "horrible noise" issue in f88faef.

**Comment by ShadowStkr** [comment] 2017-08-16 23:21
@rkitover Problem is still there, unfortunately.

**Comment by rkitover** [comment] 2017-08-17 09:58
@ShadowStkr I rewrote SoundSDL, all the crashes/hangs/deadlocks should be gone, and the audio should sound better.

Could you try again please?

**Comment by ShadowStkr** [comment] 2017-08-17 20:35
@rkitover Garbled sound in SDL is gone and no crashes or deadlocks happen when the audio is paused. However, opening the audio settings and confirming them through pressing the OK button, no matter whether I actually change them or not, simply crashes the emulator and makes it close by itself. Therefore I cannot test if #142 and #143 still happen.

**Comment by rkitover** [comment] 2017-08-17 21:05
@ShadowStkr 

#143 should be unrelated to this.

I am able to change sound settings with the dialog for GBA ROMs but not GBC ROMs on my Mac. For GBC ROMs I found issues in the emulator core that cause segfaults (#130.)

There may be similar issues in the core for GBA ROMs that just do not manifest on my Mac. I will try to test in a Linux VM as well.

If you could please give me a backtrace from the crash, that would be immensely helpful.

To generate a backtrace, run `cmake` with:

```shell
cmake .. -DCMAKE_BUILD_TYPE=Debug ...
```

then once you have the `core` file, run:

```shell
gdb -c core ./visualboyadvance-m
```

and in `gdb` type the `bt` command to get a backtrace.

I will add these instructions into the readme as well.

**Comment by ShadowStkr** [comment] 2017-08-25 07:25
So, I'm sorry for the long wait. I ended up having a hard drive crash and had to reinstall Arch and everything from the zero, which together with other things that kept me busy took me some days. Nonetheless, once everything was up and working again, I tried building the last git-master version again and somehow, it seems that the freezing when confirming audio options or loading other ROMs isn't happening anymore. However, I'm still experiencing the other bugs I opened issues about (#142 and #143).

**Comment by ShadowStkr** [comment] 2017-08-25 07:31
So, I'm sorry for the long wait. I ended up having a hard drive crash and had to reinstall Arch and everything from the zero, which together with other things that kept me busy took me some days. Nonetheless, once everything was up and working again, I tried building the last git-master version again and somehow, it seems that the freezing when confirming audio options or loading other ROMs isn't happening anymore. However, I'm still experiencing at least #143. Haven't been able to reproduce #142 for now, but I'll continue trying.

**Comment by rkitover** [comment] 2017-08-25 16:55
@ShadowStkr sorry about your hard drive crash, that is always a huge pain. I'm guessing some of this must have been related to settings in the config file. Did you have a config file created a long time ago before?

**Comment by ShadowStkr** [comment] 2017-08-25 19:46
If this file is generated automatically once the emulator options are saved for the first time, then yes, I had one and it was certainly generated with the version present in Arch's official repositories. But I didn't search for it the entire time in the previous installation, so I can't be 100% sure.

**Comment by rkitover** [comment] 2017-09-10 22:54
I've tested on Ubuntu recently, and can confirm that there is a crash when confirming the sound dialog. Will look into it further. Does not happen on mac.

**Comment by rkitover** [comment] 2017-09-21 22:55
Fixed another, and hopefully last, deadlock in SoundSDL in e9a86c5.

This one happened during the destructor for the SDL sound driver and on reset of the sound system, which happened when confirming the sound dialog.

There are still memory corruption related issues that sometimes cause a crash when confirming the sound dialog, especially with GB rather than GBA, but also with GBA, we will try to work on those next and make everything run cleanly through valgrind.

**Comment by Squall-Leonhart** [comment] 2023-07-15 06:59
Resolved now.

**Closed by Squall-Leonhart** 2023-07-15 06:59 UTC
Labels: bug, partially fixed
