### ISSUE TITLE
Stuck In Speed Up

### ISSUE THREAD

**Issue by Manlystarman** [visualboyadvance-m/visualboyadvance-m#842] opened 2021-05-04 21:46 UTC
I started up the emulator and suddenly it's running in constant fast forward? I turned it on and was playing earlier today with no issues. I just start it up and it happens for all games I try. I tried using a different version of VBA and it has the same issue. Any idea why this happened and how I can fix it?

**Comment by Squall-Leonhart** [comment] 2021-05-05 04:22
duplicate of #773

**Closed by Squall-Leonhart** 2021-05-05 04:22 UTC
