### ISSUE TITLE
VBAM is stuck at 800-900& speed as soon as I open a ROM

### ISSUE THREAD

**Issue by strydrehiryu** [visualboyadvance-m/visualboyadvance-m#851] opened 2021-05-30 17:45 UTC
### Expected behavior
Open Pokemon Radical Red (FireRed ROM patched) and the game plays normally without speed up

### Actual behavior
Open ROM on VBAM and game is already at 800-900% speed consistently

### Steps to reproduce the behavior
1. Open VBAM
2. Do either "Open" or "Open Recent" selecting Pokemon - FireRed Version (USA) (radical red patch)
3. Game already at 800-900% speed

*side note - video is set to Simple and has acted without the speed up for over a month, but now only goes to 100% speed when I'm in openGL*

### ROM details

Which games are affected by the issue (please state if GBA or GB game): Pokemon FireRed (Radical Red patch)

Include screenshots of ROM Information (File > ROM Information):
![rominfo](https://user-images.githubusercontent.com/83686045/120114419-dc0bbf80-c11a-11eb-93b4-f5b1d838df99.JPG)

### Option details

Video driver (simple, opengl): simple

Sound driver (directsound, xaudio, openal, SDL): directsound

### Build details

Operating System (Windows, Mac, Linux (state distribution), etc.): Windows 10 Home
Processor: AMD Ryzen 7 3700X 8-Core Processor 3.59 GHz
RAM: 16 GB
64-bit OS, x64-based processor

<!--- Hardware details: keyboard & mouse

**Comment by Squall-Leonhart** [comment] 2021-05-30 21:05
its not frame skipping, you've set a video filter too cpu intensive for simple graphics.

**Comment by strydrehiryu** [comment] 2021-05-31 08:05
> its not frame skipping, you've set a video filter too cpu intensive for simple graphics.

I edited the title as well as the post as I was trouble shooting. The issue now is that simple causes the speed of the ROM to jack up to 800-900% speed. I use simple in order to record since openGL has issues. Vbam was working normally on 'simple' without ever going to those speeds (checked with speed indicator) until today. When I switch it back to openGL it goes back to 100% speed (normal) but is no longer compatible with streaming/recording

**Comment by Squall-Leonhart** [comment] 2021-05-31 08:32
opengl is vsynced, simple is not (most likely)

General Settings < Throttle % of normal to 100.

**Comment by Squall-Leonhart** [comment] 2021-07-28 11:05
these are the current relevant nightlies

[visualboyadvance-m64.zip](https://github.com/visualboyadvance-m/visualboyadvance-m/files/6135345/visualboyadvance-m64.zip)

[visualboyadvance-m32.zip](https://github.com/visualboyadvance-m/visualboyadvance-m/files/6135346/visualboyadvance-m32.zip)

**Comment by Squall-Leonhart** [comment] 2021-09-24 05:13
duplicate of #773

**Closed by Squall-Leonhart** 2021-09-24 05:13 UTC
Labels: cannot reproduce
