### ISSUE TITLE
[Visual Bug] GBA: Super Bust-a-Move + BIOS

### ISSUE THREAD

**Issue by CahosRahneVeloza** [visualboyadvance-m/visualboyadvance-m#695] opened 2020-07-04 11:08 UTC
### ROM details

GBA ROM - Super Bust-a-Move
Both US and European releases on the game are affected
![Super Bust-A-Move (U) (M3)](https://user-images.githubusercontent.com/44338023/86511235-af2b2b80-be29-11ea-8d90-6811b4ed9833.png)

**Comment by rkitover** [comment] 2020-07-07 01:02
I cannot reproduce this in the current version. What version are you using? Can you try the nightly?

**Comment by CahosRahneVeloza** [comment] 2020-07-07 22:29
I am using the 2.1.4 version.

I'll try the nightly build you mentioned, but does that come in a binary/executable form as well. I ask because I do not know how to compile code, sorry.

**Comment by rkitover** [comment] 2020-07-07 23:40
It's a windows executable yes:

http://win.vba-m.com/nightly/

please try it and see if your problem is fixed, and report back here.

**Comment by CahosRahneVeloza** [comment] 2020-07-07 23:46
Okay, I tried the nightly build (June 30, 2020) and the first thing I noticed was the screen can't be resized. You can resized the window, even go fullscreen. But the video still retains the small size it has. Second, the colors are off. And when I try this game in question, my gamepad controls become inactive after I select the game's language option so I can't proceed to the ingame map view to check the issue.

**Comment by rkitover** [comment] 2020-07-08 01:16
Try going to `Help -> Factory Reset` and restart the program.

**Comment by CahosRahneVeloza** [comment] 2020-07-08 01:58
> 
> 
> Try going to `Help -> Factory Reset` and restart the program.

Factory reset did fix the resolution issue I was having and it did fix the input issue as well but the game still looks the same once I get to the map. Also the colors are still off. 
![Super Bust-A-Move (U) (M3)](https://user-images.githubusercontent.com/44338023/86865445-92c91080-c101-11ea-8e23-78198ecf6cec.png)

**Comment by denisfa** [comment] 2020-07-08 02:25
@CahosRahneVeloza 

Where is your `vbam.ini` located? Is it in the same folder of `visualboyadvance-m.exe`? If that is the case, could you attach this file to your original comment, please?

> nightly build (June 30, 2020)

The nightly has extra UI options available, some of these are enabled by default. I am using the nightly build for answering you.

>  first thing I noticed was the screen can't be resized. You can resized the window, even go fullscreen. But the video still retains the small size it has. 

`Options` > `Video` > `Configure ...`

Go to `Zoom` tab. Check the value for `Maximum magnification factor`. Set the value to `0`.

> Second, the colors are off. 

After you load the game, check

`Options` > `Game Boy Advance` > `LCD Filter`

This option is not available on the stable version, but it is hard-coded to act like it is NOT checked. On the nightly you can toggle it. Check the results with the option enabled/disabled on nightly. You probably will disable it to match the result from the stable version.

> And when I try this game in question, my gamepad controls become inactive after I select the game's language option so I can't proceed to the ingame map view to check the issue.

I have two guesses here. Could you try to map inputs to your controller after this moment? 
By `Options` > `Input` > `Configure ...`  and see if your controller is still visible to our app.

> Also, I tried the 64bit version as I've been using the 64bit version of vba-m for years now.

I am using the Linux x64 build for this screenshot. The same result applies for the latest stable version, `2.1.4`.

![Super Bust-A-Move (USA) (En,Fr,Es)](https://user-images.githubusercontent.com/11354751/86866092-ab580d00-c0a6-11ea-80c7-4183f0c12e70.png)

Unless you have new information here, like playing a hack, patched version or something, I have no idea what can be happening (you can attach a screenshot of `File` > `ROM Information` so we can rule the hack out).

**Comment by CahosRahneVeloza** [comment] 2020-07-08 03:25
@denisfa:

vba.ini file for the latest stable version 2.1.4:

[vbam214.zip](https://github.com/visualboyadvance-m/visualboyadvance-m/files/4888175/vbam214.zip)

Recording of the issue:
[Super Bust-A-Move (U) (M3).zip](https://github.com/visualboyadvance-m/visualboyadvance-m/files/4888179/Super.Bust-A-Move.U.M3.zip)

[quote]I am using the Linux x64 build for this screenshot. The same result applies for the latest stable version, 2.1.4.[/quote]
I am using the 64bit Windows version, if that helps.

Recording using the nightly build (June 30th, 2020)
[Nightly build video.zip](https://github.com/visualboyadvance-m/visualboyadvance-m/files/4888221/Nightly.build.video.zip)

Nightly build with the LCD Filter unchecked:
[Nightlybuildvideonolcdfilter.zip](https://github.com/visualboyadvance-m/visualboyadvance-m/files/4888249/Nightlybuildvideonolcdfilter.zip)

**Comment by denisfa** [comment] 2020-07-08 03:49
@CahosRahneVeloza Thank you! I found the issue: this happens when you boot using a GBA BIOS.

Ok, at least I found the cause here. We will see what to do next.

**Comment by CahosRahneVeloza** [comment] 2020-07-08 03:53
I forgot to post the ROM Information...
![Untitled](https://user-images.githubusercontent.com/44338023/86873741-906eb280-c111-11ea-977f-90ac870e41e8.png)

**Comment by rkitover** [comment] 2020-07-08 19:54
@denisfa How would we do this, trace bios calls during that segment of the game and see what is different?

**Comment by CahosRahneVeloza** [comment] 2020-07-09 03:36
Wait...

So my issue is caused by the fact I run vba-m with BIOSes? But I thought using BIOSes made emulators better? I've been running visualboyadvance with the GBA BIOS ever since vba 1.7.2 And in fact hack in those days the BIOS was important. The old vba-over.ini file was even important back in the day, especially when running games like the third Gen Pokemon titles. Even after switching over to vba-m back in 2016 I still run the Emulator with BIOSes enabled.

**Comment by rkitover** [comment] 2020-07-09 04:49
Generally these days the BIOS is not needed, except in some rare cases where it makes link work better. Also @denisfa fixed your bug, just waiting for him to merge it and then it will be in the nightly.

**Comment by CahosRahneVeloza** [comment] 2020-07-09 07:16
> Generally these days the BIOS is not needed, except in some rare cases where it makes link work better. Also @denisfa fixed your bug, just waiting for him to merge it and then it will be in the nightly.

Cool 👍

You guys work fast. By the way  forgive me for asking, if it's against the rules, but are you the folks who used to work om vba-m and would often release various builds on the old vba-m forums? I used to keep an eye on those torums for the latest builds 😊

**Comment by rkitover** [comment] 2020-07-09 08:25
The forum is still available at https://board.vba-m.com/. We just recently brought it back online. Neither me or denisfa go that far back but @ZachBacon does.

We actually really need to do a new release, also.

**Comment by rkitover** [comment] 2020-07-10 23:26
The nightly has the fix now, could you please try it and see if your issue is resolved?

**Comment by CahosRahneVeloza** [comment] 2020-07-11 02:09
> 
> 
> The nightly has the fix now, could you please try it and see if your issue is resolved?

Tested with a demo video showing that everything's fixed now :)
[NightlyDemo.zip](https://github.com/visualboyadvance-m/visualboyadvance-m/files/4906135/NightlyDemo.zip)

Thank you  both for the quick responses and fix.

**Comment by rkitover** [comment] 2020-07-11 02:18
Excellent, thank you!

**Closed by rkitover** 2020-07-11 02:18 UTC
Labels: bug, gba core
