### ISSUE TITLE
Pressing key 1 to 5 change screen size instead of input in number

### ISSUE THREAD

**Issue by crest1993** [visualboyadvance-m/visualboyadvance-m#600] opened 2020-02-01 03:53 UTC
### Please fill out this form:

Pressing key board number (not numkey, num key works as is) 1 to 5 change the screen scale / size instead of input number in cheats searching or anywhere.

Things i did
- open ROM
- list cheats, add code and then can't even put number anywhere
- this happen not only in cheat list, memory view too or maybe everywhere else.

even if i've already remove hotkey from option still can't input number.

### ROM details

FIRE RED with rom hack adventure red chapter b15.4

### Option details

Video driver (simple, opengl): OPENGL

Sound driver (directsound, xaudio, openal, SDL): Directsound

### Build details

Operating System (Windows, Mac, Linux (state distribution), etc.):
Windows 10 64 bit build 1803

Version of code (pre-built binary version, or commit ref, or just "master"):

Visualboyadvance-m 2.1.4

**Comment by denisfa** [comment] 2020-02-01 03:57
@crest1993 Thank you for the report. This is a duplicate of #516. Is has been fixed already, it will be available next release.

Download the nightly with the fix [here](https://github.com/visualboyadvance-m/visualboyadvance-m/issues/354#issuecomment-568932350).

**Closed** 2020-02-01 03:57 UTC
Labels: duplicate
