### ISSUE TITLE
Issue streaming to Discord

### ISSUE THREAD

**Issue by JeremyStacy** [visualboyadvance-m/visualboyadvance-m#840] opened 2021-04-28 16:11 UTC
Expected behavior 

I stream the game through Discord by sharing my application.

Actual behavior

The emulator screen just stays black until I stop streaming through Discord and close the ROM and reopen it. The game audio still plays though.

Steps to reproduce the behavior

- Share the emulator screen through Discord stream.
- Open ROM (I decided to try Pokemon Ruby).
- Both screens on the Discord and the emulator are black screens.
- (You can swap the order of the first 2 steps and the bug still appears.)

ROM details

Which games are affected by the issue (please state if GBA or GB game): 

I only tested this with Pokemon Ruby as it's the only ROM I have (I did a college assignment involving Visual Boy before and used Ruby for it)

Include screenshots of ROM Information (File > ROM Information):

![image](https://user-images.githubusercontent.com/42854517/116436409-614d3d00-a81a-11eb-8635-6cb0da56a0a0.png)

Option details

Video driver (simple, opengl):

OpenGL

Sound driver (directsound, xaudio, openal, SDL):

SDL

### Build details

Operating System (Windows, Mac, Linux (state distribution), etc.):

Windows

Version of code (pre-built binary version, or commit ref, or just "master"):

VisualBoyAdvance-M 2.1.4

**Comment by Squall-Leonhart** [comment] 2021-04-28 17:16
Discord has poor support for OpenGL streaming, use Simple.

**Comment by JeremyStacy** [comment] 2021-04-28 17:18
Noted, thank you!

**Comment by Squall-Leonhart** [comment] 2021-04-28 17:27
For reference, its the "use our latest technology to capture your screen" that causes the  black screen on the emulator, but under opengl you still won't get video to show in discord.

Other opengl titles have been noted to have streaming issues, and many more reported to run fine, its probably fixable on our end as much as discords end.

That said i don't know what opengl Wx targets, since i don't think we create the opengl renderer ourselves under Wx.

**Comment by JeremyStacy** [comment] 2021-04-28 17:29
Ok, good to know. That's interesting.

**Comment by Squall-Leonhart** [comment] 2021-04-28 17:38
@ZachBacon @rkitover are we Wx 2.9 compliant?

**Comment by ZachBacon** [comment] 2021-04-28 17:40
> @ZachBacon @rkitover are we Wx 2.9 compliant?

We default now basically to 3.0 and higher, but I think @rkitover left some compatibility to the 2.x series.

**Comment by Squall-Leonhart** [comment] 2021-04-28 17:58
Ah, we are still using Implicit contexts for WxGL contexts, this may be a factor in this bug.

**Comment by Squall-Leonhart** [comment] 2021-09-24 05:19
duplicate of #767

**Closed by Squall-Leonhart** 2021-09-24 05:19 UTC

**Comment by Squall-Leonhart** [comment] 2023-07-09 02:34
Based on eduke32's method, this has been fixed in https://github.com/visualboyadvance-m/visualboyadvance-m/compare/discord-fix and will be merged to master after some testing.

Try this
[visualboyadvance-m.zip](https://github.com/visualboyadvance-m/visualboyadvance-m/files/11964207/visualboyadvance-m.zip)
