### ISSUE TITLE
[Bug]: When I save state, it saves with 01/01/1970 date

### ISSUE THREAD

**Issue by santo998** [visualboyadvance-m/visualboyadvance-m#1269] opened 2024-04-02 13:46 UTC
### Expected behavior?

Saved state has actual date

### Actual behavior?

I think my emulator's date overflowed some way.

When I save state, it saves it as xx/xx/1970.

I tried different games, and the same happens. So I think the problem is on VisualBoyAdvance-M.

Any clues on how to fix this?

### Steps to reproduce the problem

1. Save an state

### Error messages?

No

### What game were you playing

It happens with all kind of games...
Just an example:

Title: Shining Soul II (USA)
GB, GBC or GBA: GBA
ROM CODE: 
BIOS Used?: None
SAVE TYPE: automatic, 64 K
Clean, Intro'd or Hacked?: Clean

### What settings are you using?

Video driver (simple, opengl): OpenGL
Sound driver (directsound, xaudio, openal, SDL): XAudio2
Scale Filter Used?: No

### Specifications and Build details

VBA-M: 2.1.9 64 bits
OS: Windows 11 version 23H2 (OS Build 22631.3296)
CPU: Ryzen 5 3400g
GPU: Vega 11 integrated graphics
RAM: 16 GB

### Copyright Compliance

- [X] There are no infringing files attached to this bug report.

**Comment by ZachBacon** [comment] 2024-04-02 14:39
Duplicate of https://github.com/visualboyadvance-m/visualboyadvance-m/discussions/1264

**Closed by ZachBacon** 2024-04-02 14:39 UTC
Labels: bug

**Comment by santo998** [comment] 2024-04-02 14:56
@ZachBacon reopen this, as the link you tagged is a closed discussion

**Comment by ZachBacon** [comment] 2024-04-02 14:57
Not anymore.
