### ISSUE TITLE
[Bug]: Cable Club Red/Blue/Yellow

### ISSUE THREAD

**Issue by GlitchTheG4mer** [visualboyadvance-m/visualboyadvance-m#1388] opened 2024-12-22 02:13 UTC
### Expected behavior?

You should be able to trade between these games once linked.

### Actual behavior?

I have attempted to connect ta "link cable" and succeeded but every time I try to trade in pokemon red version, it keeps saying "welcome to the cable club! This area is reserved for 2 friends connected via link cable." and won't let me trade, even though I have made sure both players are connected, and I have even changed the link type to no avail.

### Steps to reproduce the problem

1.Set up link cable
2.Talk to the woman at the pokemon center
3.There is no step 3.

### Error messages?

If this is a crash bug, and you have the time and inclination, please provide a symbolic backtrace.
Instructions for doing so are [here](https://github.com/visualboyadvance-m/visualboyadvance-m/blob/master/README.md#reporting-crash-bugs).

### What game were you playing

![Screenshot 2024-12-21 190835](https://github.com/user-attachments/assets/f3ff9ded-3419-4031-816f-2fab063a4e41)

### What settings are you using?

Video driver (simple, opengl):
Sound driver (directsound, xaudio, openal, SDL):
Scale Filter Used?:

### Specifications and Build details

VBA-M: (I don't know, but it is the most recent 64-bit version as of 12/21/2024
OS: (Windows 11 Home):
CPU:AMD Ryzen 3 4300U with Radeon Graphics
GPU:AMD Radeon(TM) Graphics
RAM:8.00 GB (7.39 GB usable)

### Copyright Compliance

- [X] There are no infringing files attached to this bug report.

**Comment by Squall-Leonhart** [comment] 2024-12-22 02:16
Duplicate of 50 other issues

Closed

**Closed by Squall-Leonhart** 2024-12-22 02:16 UTC
Labels: bug
