### ISSUE TITLE
[Bug]: No Audio and Game Stuck in Turbo

### ISSUE THREAD

**Issue by gregdos910** [visualboyadvance-m/visualboyadvance-m#1283] opened 2024-04-17 02:12 UTC
### Expected behavior?

I was expecting audio and normal game speed.

### Actual behavior?

The game has no audio and is stuck in turbo speed.

### Steps to reproduce the problem

1. I opened VisualBoy Advance 
2. I opened a ROM
3. A dialog box pops up, stating: Could not initialize the sound driver!
4. I click "Details" in the dialog box.
5. It says: The XAudio2 interface failed to initialize! And also says: Could not initialize the sound driver! 
...

### Error messages?

Yes. A dialog box pops up, stating: Could not initialize the sound driver! I click "Details" in the dialog box.
It says: The XAudio2 interface failed to initialize! 
And also says: Could not initialize the sound driver! 

### What game were you playing

I opened Drill Dozer, and also multiple other games. It had the same issue with all.

### What settings are you using?

Video driver (simple, opengl): Intel(R) HD Graphics 630
Sound driver (directsound, xaudio, openal, SDL): Focusrite USB Audio
Scale Filter Used?: I'm not sure
![Screenshot (1)](https://github.com/visualboyadvance-m/visualboyadvance-m/assets/167268050/5250ad51-7d13-4c8f-be0b-61071016007c)

### Specifications and Build details

VBA-M: (include commit version number and whether you are using the 32-bit or 64-bit version) Version 2.1.5.0 64-bit
OS: (include version and OS build number using WinVer if on Windows): Microsoft Windows 10 Pro Version 10.0.19045 Build 19045
If using Linux, specify if using xorg or Wayland:
CPU: Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz   3.60 GHz
GPU: Intel(R) HD Graphics 630
RAM: 32.0 GB (31.9 GB usable)

### Copyright Compliance

- [X] There are no infringing files attached to this bug report.

**Comment by ZachBacon** [comment] 2024-04-17 02:25
You're using an outdated version we're at version 2.1.9, download that from the release tab on our GitHub page or download a nightly from https://nightly.visualboyadvance-m.org

**Comment by Squall-Leonhart** [comment] 2024-04-17 02:26
Duplicate of https://github.com/visualboyadvance-m/visualboyadvance-m/issues/1278

**Closed by Squall-Leonhart** 2024-04-17 02:26 UTC
Labels: bug
