### ISSUE TITLE
Choppy Framerate on Windows with SDL sound driver

### ISSUE THREAD

**Issue by briansrls** [visualboyadvance-m/visualboyadvance-m#709] opened 2020-08-08 16:10 UTC
### Expected behavior
Smoother framerate.  To be clear, I am not sure if issue is actually framerate.  Anecdotally, I see it drop to 58 fps regularly during these micro stutters, and when things are more clear it shows 60.  It may take more analysis to determine the actual issue.

### Actual behavior
Getting micro stutters, demonstrated in video.  The leftmost screen is getting small stutters as I move:
https://streamable.com/pv2544

Leftmost is VBAM 2.14, middle is Retroarch running VBAM core 2.1.3, and right is mGBA.

### Steps to reproduce the behavior
Issue is very consistent, regardless of config.  I have not tried games other than Pokemon.  Factory reset, except bilinear filter disabled (does not make a difference, issue is seen with and without bilinear filter).  I am running on windows, have not tried on linux.  Will try on a VM later.

### ROM details

Which games are affected by the issue (please state if GBA or GB game):
I have tested various pokemon games, third generation (GBA) and also pokemon crystal (GB).  I see this issue present in both.

Which games, if any, are NOT affected by the issue (please state if GBA or GB game):
I have always seen this issue, but I have not tested many games.

Include screenshots of ROM Information (File > ROM Information):
![image](https://user-images.githubusercontent.com/11205878/89714797-33eff480-d956-11ea-8127-306efd973b42.png)
Issue happens regardless of ROM

If you are using a BIOS file, please say which one.
N/A

### Option details

Video driver (simple, opengl):
opengl

Sound driver (directsound, xaudio, openal, SDL):
SDL

### Build details

Operating System (Windows, Mac, Linux (state distribution), etc.):
Windows

Version of code (pre-built binary version, or commit ref, or just "master"):
I see this issue with built master, and also with binaries downloaded from releases.

**Comment by negativeExponent** [comment] 2020-08-09 02:47
what gpu is this? just a guess, but you might need to make sure vsync is enabled for your compositor/xorg driver (i need to do this on my intel gpu).

**Comment by rkitover** [comment] 2020-08-09 07:15
Please get the latest nightly from http://win.vba-m.com/nightly and try turning on `Emulation -> Vsync`. Thanks to @negativeExponent for the idea.

**Comment by briansrls** [comment] 2020-08-10 04:04
Hi all, thank you for the tips, I was actually able to solve my issue by switching my audio config from SDL to directsound.  Maybe it's an audio sync issue?

**Comment by rkitover** [comment] 2020-08-10 20:49
The way this emulator works, is the emulation is synced to the sound driver.

Just out of curiosity, what is your hardware configuration, how many cores etc. and what is the sound device/driver.

SDL is our primary sound driver, in some cases it works even better than the directsound driver on Windows, but perhaps we should revert to making directsound the default driver on Windows.

@denisfa would c6fb0d5 be relevant here, should I cherry-pick that to master and see if it helps?

**Comment by briansrls** [comment] 2020-08-10 21:33
I have reproduced this on two devices,

One a desktop with an overclocked 10900k, (10 cores 5.2Ghz), and the sound device is a speaker coming out of my motherboard, as well as a thunderbolt dock.  I have tried the generic microsoft sound drivers, and also just installed raeltek drivers but see the issue regardless.

The other is my laptop, it has an 8750H (6 cores 4.2ghz), and the sound device are the laptop speakers (and the drivers are generic microsoft).

After my testing, I support making directsound the default driver until we can resolve this issue.

@rkitover I will try c6fb0d5 and let you know if it helps.

**Comment by rkitover** [comment] 2020-08-10 22:05
@briansrls thank you, I will wait for your results and then make this change if necessary. I think some other people reported this issue as well.

**Comment by briansrls** [comment] 2020-08-10 23:19
I didn't notice any impact when I modified the buftime

**Comment by rkitover** [comment] 2020-08-11 07:11
@briansrls Great, thank you for testing.

@denisfa I was thinking about the best way to handle these issues, and I had an idea, why don't we set default config settings to the string `default` instead of a specific setting, that way we can change defaults and users will be updated appropriately.

**Comment by briansrls** [comment] 2020-08-30 04:59
I was testing this more tonight.  I actually noticed that changing the frequency compounded the issue.  11khz was extremely slow, while 44 was much better.

**Comment by briansrls** [comment] 2020-08-30 05:03
Also, I have a strong feeling this issue exists on Linux as well.  This is an issue, because the only alternative to SDL on linux is openal right now.

**Comment by rkitover** [comment] 2020-09-04 06:34
Right so, we were going to switch to DirectSound as the default on Windows again, I will do this soon.

One thing you should understand, is that the speed of the sound driver controls the game speed, when we do things like throttle or turbo all of that is based on changing the speed of the sound driver.

**Comment by ltlynx** [comment] 2020-10-17 19:12
Some time ago I wrote for the exact same issue. Direct sound was the best option also for me, but framerate is still choppy (98-100%) regardless of configuration.

**Comment by TheRealDannyyy** [comment] 2021-04-07 15:26
> Some time ago I wrote for the exact same issue. Direct sound was the best option also for me, but framerate is still choppy (98-100%) regardless of configuration.

I have the same issue with VBA getting choppy on my high-end setup. Switching to DirectSound didn't help at all on my end.
This seems to be caused by something else. Not sure how to properly debug this, help is appreciated!

**Comment by Hexaae** [comment] 2021-04-24 12:28
I use for my tests Metroid Fusion.
Confirmed that DSound improves things removing additional micro-stuttering, but still won't make it smooth as I expected :(
The online emulator https://emulatorgames.online/games/gba/metroid-fusion looks smoother (but not perfect yet) in Edge Chromium than VBA-M.
I've also noticed full screen is actually borderless full window (?), and not Full screen **exclusive** which could benefit for example from G-Sync...

Win 10 20H2, i7-8750H (6+6 threads), 32GB, 1070 8GB VRAM, NVidia 462.31.

**Comment by Squall-Leonhart** [comment] 2021-04-24 12:33
We need to implement an option to directly use WASAPI or PortAudio instead of going through Dsound or SDL, 

Both of these are just mixed and layered on top of wasapi anyway with windows and add to timings being off, as well as abnormal performance when using a limiter based on audio.

**Comment by Hexaae** [comment] 2021-04-27 07:12
Full screen exclusive (not borderless full window) couldn't also help for improved smoothness (especially on G-Sync screens)?

**Comment by briansrls** [comment] 2021-04-28 00:53
I spent a lot of time debugging this issue.  I wasn't able to determine the cause.  I was able to verify that 60 frames are being produced by VBA every second, seems like a frame pacing issue?  Vertical sync didn't seem to help solve this issue.  It clearly didn't "look" like 60fps when I was debugging it.

**Comment by Squall-Leonhart** [comment] 2024-01-01 06:55
This issue should be since resolved by having fully enabled code optimizations after 2.1.5, a point value frame limiter may see fps drop to 58 minimum but this is within the expected range for a 60hz vsync. (58.4-61.2)

**Comment by rkitover** [comment] 2024-01-19 01:25
@GrEgStAr3000 and anyone else who is still following this, can you please do me a favor and check of the frame rate choppiness happens with the OpenAL sound driver. If it does not, I will just remove the SDL sound driver and make OpenAL the default.

**Closed** 2024-02-03 21:03 UTC
Labels: bug, sound, UI Win
